In [1]:
import pandas as pd
import numpy as np

In [2]:
freq=pd.read_csv("F:\\project\\Group2\\freMTPL2freq.csv")
sev=pd.read_csv("F:\\project\\Group2\\freMTPL2sev.csv")

In [3]:
freq.head()

,IDpol,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Area,Density,Region
0,1.0,0,0.10,5,0,55,50,B12,Regular,D,1217,Rhone-Alpes
1,3.0,0,0.77,5,0,55,50,B12,Regular,D,1217,Rhone-Alpes
2,5.0,0,0.75,6,2,52,50,B12,Diesel,B,54,Picardie
3,10.0,0,0.09,7,0,46,50,B12,Diesel,B,76,Aquitaine
4,11.0,0,0.84,7,0,46,50,B12,Diesel,B,76,Aquitaine

In [4]:
sev.head()

     IDpol  ClaimAmount
0     1552       995.20
1  1010996      1128.12
2  4024277      1851.11
3  4007252      1204.00
4  4046424      1204.00

In [5]:
freq.tail()

,IDpol,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Area,Density,Region
677986,6114326.0,0,0.00274,4,0,54,50,B12,Regular,E,3317,Provence-Alpes-Cotes-D'Azur
677987,6114327.0,0,0.00274,4,0,41,95,B12,Regular,E,9850,Ile-de-France
677988,6114328.0,0,0.00274,6,2,45,50,B12,Diesel,D,1323,Rhone-Alpes
677989,6114329.0,0,0.00274,4,0,60,50,B12,Regular,B,95,Bourgogne
677990,6114330.0,0,0.00274,7,6,29,54,B12,Diesel,B,65,Aquitaine

In [6]:
sev.tail()

         IDpol  ClaimAmount
26439  3254353      1200.00
26440  3254353      1800.00
26441  3254353      1000.00
26442  2222064       767.55
26443  2254065      1500.00

In [7]:
freq.shape

(677991, 12)

In [8]:
sev.shape

(26444, 2)

In [9]:
freq.columns

Index(['IDpol', 'ClaimNb', 'Exposure', 'VehPower', 'VehAge', 'DrivAge',
       'BonusMalus', 'VehBrand', 'VehGas', 'Area', 'Density', 'Region'],
      dtype='object')

In [10]:
sev.columns

Index(['IDpol', 'ClaimAmount'], dtype='object')

In [11]:
freq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 677991 entries, 0 to 677990
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   IDpol       677991 non-null  float64
 1   ClaimNb     677991 non-null  int64
 2   Exposure    677991 non-null  float64
 3   VehPower    677991 non-null  int64
 4   VehAge      677991 non-null  int64
 5   DrivAge     677991 non-null  int64
 6   BonusMalus  677991 non-null  int64
 7   VehBrand    677991 non-null  object
 8   VehGas      677991 non-null  object
 9   Area        677991 non-null  object
 10  Density     677991 non-null  int64
 11  Region      677991 non-null  object
dtypes: float64(2), int64(6), object(4)
memory usage: 62.1+ MB

In [12]:
sev.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26444 entries, 0 to 26443
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   IDpol        26444 non-null  int64
 1   ClaimAmount  26444 non-null  float64
dtypes: float64(1), int64(1)
memory usage: 413.3 KB

In [13]:
freq.describe()

,IDpol,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,Density
count,6.779910e+05,677991.000000,677991.000000,677991.000000,677991.000000,677991.000000,677991.000000,677991.000000
mean,2.621886e+06,0.039003,0.528743,6.454649,7.044244,45.499092,59.761559,1792.406856
std,1.641776e+06,0.207169,0.364441,2.050914,5.666226,14.137449,15.636713,3958.574057
min,1.000000e+00,0.000000,0.002732,4.000000,0.000000,18.000000,50.000000,1.000000
25%,1.157964e+06,0.000000,0.180000,5.000000,2.000000,34.000000,50.000000,92.000000
50%,2.272157e+06,0.000000,0.490000,6.000000,6.000000,44.000000,50.000000,393.000000
75%,4.046271e+06,0.000000,0.990000,7.000000,11.000000,55.000000,64.000000,1658.000000
max,6.114330e+06,16.000000,2.010000,15.000000,100.000000,100.000000,230.000000,27000.000000

In [14]:
sev.describe()

              IDpol   ClaimAmount
count  2.644400e+04  2.644400e+04
mean   2.280004e+06  2.265513e+03
std    1.583004e+06  2.937103e+04
min    1.390000e+02  1.000000e+00
25%    1.086381e+06  6.859925e+02
50%    2.133756e+06  1.172000e+03
75%    3.183953e+06  1.212385e+03
max    6.113971e+06  4.075401e+06

In [15]:
freq.isnull().sum()

IDpol         0
ClaimNb       0
Exposure      0
VehPower      0
VehAge        0
DrivAge       0
BonusMalus    0
VehBrand      0
VehGas        0
Area          0
Density       0
Region        0
dtype: int64

In [16]:
freq.isnull().mean()*100

IDpol         0.0
ClaimNb       0.0
Exposure      0.0
VehPower      0.0
VehAge        0.0
DrivAge       0.0
BonusMalus    0.0
VehBrand      0.0
VehGas        0.0
Area          0.0
Density       0.0
Region        0.0
dtype: float64

In [17]:
sev.isnull().sum()

IDpol          0
ClaimAmount    0
dtype: int64

In [18]:
sev.isnull().mean()*100

IDpol          0.0
ClaimAmount    0.0
dtype: float64

In [19]:
freq.duplicated().sum()

np.int64(0)

In [20]:
sev.duplicated().sum()

np.int64(235)

In [21]:
freq[freq.duplicated()]

Empty DataFrame
Columns: [IDpol, ClaimNb, Exposure, VehPower, VehAge, DrivAge, BonusMalus, VehBrand, VehGas, Area, Density, Region]
Index: []

In [22]:
sev[sev.duplicated()]

         IDpol  ClaimAmount
162    4023587       1204.0
312    4055082       1204.0
315    4044981       1204.0
399    4041886       1204.0
409    4073123       1204.0
...        ...          ...
26308  3253234       1500.0
26309  3253234       1500.0
26439  3254353       1200.0
26440  3254353       1800.0
26441  3254353       1000.0

[235 rows x 2 columns]

In [23]:
# check IDpol
freq["IDpol"].isnull().sum()

np.int64(0)

In [24]:
# check IDpol
sev["IDpol"].isnull().sum()

np.int64(0)

In [25]:
freq["IDpol"].duplicated().sum()

np.int64(0)

In [26]:
sev["IDpol"].duplicated().sum()

np.int64(1500)

In [27]:
sev["IDpol"].duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
26439     True
26440     True
26441     True
26442    False
26443    False
Name: IDpol, Length: 26444, dtype: bool

In [28]:
freq[freq.duplicated(keep=False)]

Empty DataFrame
Columns: [IDpol, ClaimNb, Exposure, VehPower, VehAge, DrivAge, BonusMalus, VehBrand, VehGas, Area, Density, Region]
Index: []

In [29]:
sev[sev.duplicated(keep=False)].sort_values("IDpol").head(20)

       IDpol  ClaimAmount
6355   18698      1128.12
5022   18698      1128.12
4514   19887      1128.12
4521   19887      1128.12
6322   24992      1128.12
6318   24992      1128.12
5862   25763      1128.12
5866   25763      1128.12
24094  29567      1128.12
24096  29567      1128.12
4456   47912      1128.12
4457   47912      1128.12
20862  54009      1128.12
21030  54009      1128.12
20115  57501      1128.12
19929  57501      1128.12
24212  58271      1128.12
24177  58271      1128.12
6358   63581      1128.12
5094   63581      1128.12

In [30]:
sev.duplicated().sum()

np.int64(235)

In [31]:
sev[sev.duplicated(keep=False)].head(20)

       IDpol  ClaimAmount
42   4023587       1204.0
108  4041886       1204.0
162  4023587       1204.0
192  4055082       1204.0
238  4044981       1204.0
264  4085358       1204.0
296  4037199       1204.0
307  4073123       1204.0
312  4055082       1204.0
315  4044981       1204.0
324  4049000       1204.0
398  4042068       1204.0
399  4041886       1204.0
409  4073123       1204.0
455  4049000       1204.0
476  4041055       1204.0
484  4052004       1204.0
586  4052004       1204.0
646  4031494       1204.0
655  4031494       1204.0

In [32]:
sev[sev.duplicated(keep=False)].sort_values(["IDpol","ClaimAmount"]).head(60)

        IDpol  ClaimAmount
5022    18698      1128.12
6355    18698      1128.12
4514    19887      1128.12
4521    19887      1128.12
6318    24992      1128.12
6322    24992      1128.12
5862    25763      1128.12
5866    25763      1128.12
24094   29567      1128.12
24096   29567      1128.12
4456    47912      1128.12
4457    47912      1128.12
20862   54009      1128.12
21030   54009      1128.12
19929   57501      1128.12
20115   57501      1128.12
24177   58271      1128.12
24212   58271      1128.12
5094    63581      1128.12
6358    63581      1128.12
16767   64373      1128.12
16993   64373      1128.12
6170    64761      1128.12
6175    64761      1128.12
5912    69710      1128.12
5913    69710      1128.12
10401   78130      1128.12
10450   78130      1128.12
5879    80499      1128.12
6210    80499      1128.12
5846    82396      1128.12
5860    82396      1128.12
5699    84575      1128.12
5705    84575      1128.12
5715    84723      1128.12
5723    84723      1128.12
5670    85694      1128.12
5681    85694      1128.12
6338    87044      1128.12
18364   87044      1128.12
4932    93954      1128.12
4949    93954      1128.12
4964    93954      1128.12
4988    93954      1128.12
18374   94483      1128.12
18434   94483      1128.12
17488   99249      1128.12
17492   99249      1128.12
24070  106146      1128.12
24071  106146      1128.12
13661  107107      1128.12
13957  107107      1128.12
21486  109352      1128.12
22185  109352      1128.12
20181  130375      1128.12
20653  130375      1128.12
10738  131884      1128.12
10994  131884      1128.12
4843   138936      1128.12
4881   138936      1128.12

In [33]:
duplicate_groups=(sev.groupby(["IDpol","ClaimAmount"]).size().reset_index(name="count"))
duplicate_groups=duplicate_groups[duplicate_groups["count"]>1]
duplicate_groups.head(60)

        IDpol  ClaimAmount  count
144     18698      1128.12      2
177     19887      1128.12      2
305     24992      1128.12      2
321     25763      1128.12      2
423     29567      1128.12      2
1001    47912      1128.12      2
1180    54009      1128.12      2
1279    57501      1128.12      2
1308    58271      1128.12      2
1478    63581      1128.12      2
1505    64373      1128.12      2
1529    64761      1128.12      2
1718    69710      1128.12      2
2019    78130      1128.12      2
2086    80499      1128.12      2
2139    82396      1128.12      2
2215    84575      1128.12      2
2221    84723      1128.12      2
2251    85694      1128.12      2
2290    87044      1128.12      2
2478    93954      1128.12      4
2505    94483      1128.12      2
2627    99249      1128.12      2
2840   106146      1128.12      2
2854   107107      1128.12      2
2905   109352      1128.12      2
3184   130375      1128.12      2
3224   131884      1128.12      2
3403   138936      1128.12      2
3423   139553      1128.12      2
3445   140398      1128.12      2
3461   141105      1128.12      2
3463   141256      1128.12      2
3662   149242      1128.12      2
4049   162695      1128.12      2
4078   163865      1128.12      2
4079   163873      1128.12      2
4297   171580      1128.12      2
4307   172022      1128.12      2
4320   172452      1128.12      2
4419   176081      1128.12      2
4447   176728      1128.12      2
4454   176908      1128.12      2
4899  1019419      1128.12      2
4944  1021466      1128.12      2
5145  1032003      1128.12      2
5964  1065109      1128.00      2
6300  1077644      1128.12      2
6373  1079938      1128.12      2
6490  1084245      1128.12      2
6520  1085175      1128.12      2
6527  1085375      1128.00      2
6670  1090455      1128.12      2
6689  1091000      1128.12      2
6912  1097391      1128.12      2
6927  1097726      1128.12      2
7075  1101835      1128.12      2
7706  1118709      1128.00      2
7836  1121261      1128.12      2
7888  1122437      1128.12      2

In [34]:
sev[sev["IDpol"]==18698]

      IDpol  ClaimAmount
5022  18698      1128.12
6355  18698      1128.12

In [35]:
sev[sev["IDpol"].isin([18698,19887,24992,25763])]

      IDpol  ClaimAmount
4514  19887      1128.12
4521  19887      1128.12
5022  18698      1128.12
5862  25763      1128.12
5866  25763      1128.12
6318  24992      1128.12
6322  24992      1128.12
6355  18698      1128.12

In [36]:
freq[freq["IDpol"].isin([18698,19887,24992,25763])]

,IDpol,ClaimNb,Exposure,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Area,Density,Region
6136,18698.0,2,1.0,6,12,86,50,B1,Regular,C,227,Poitou-Charentes
6756,19887.0,2,1.0,5,17,58,102,B1,Regular,A,44,Centre
9407,24992.0,2,1.0,6,6,23,112,B2,Diesel,B,61,Centre
9844,25763.0,2,1.0,4,6,54,77,B2,Diesel,A,10,Limousin

In [37]:
check_ids=[18698,19887,24992,25763]
print("severity:")
print(sev[sev["IDpol"].isin(check_ids)].sort_values("IDpol"))
print("\nFrequency:")
print(freq[freq["IDpol"].isin(check_ids)].sort_values("IDpol"))

severity:
      IDpol  ClaimAmount
5022  18698      1128.12
6355  18698      1128.12
4514  19887      1128.12
4521  19887      1128.12
6318  24992      1128.12
6322  24992      1128.12
5862  25763      1128.12
5866  25763      1128.12

Frequency:
        IDpol  ClaimNb  Exposure  VehPower  VehAge  DrivAge  BonusMalus  \
6136  18698.0        2       1.0         6      12       86          50
6756  19887.0        2       1.0         5      17       58         102
9407  24992.0        2       1.0         6       6       23         112
9844  25763.0        2       1.0         4       6       54          77

     VehBrand   VehGas Area  Density            Region
6136       B1  Regular    C      227  Poitou-Charentes
6756       B1  Regular    A       44            Centre
9407       B2   Diesel    B       61            Centre
9844       B2   Diesel    A       10          Limousin

In [38]:
freq.dtypes

IDpol         float64
ClaimNb         int64
Exposure      float64
VehPower        int64
VehAge          int64
DrivAge         int64
BonusMalus      int64
VehBrand       object
VehGas         object
Area           object
Density         int64
Region         object
dtype: object

In [39]:
sev.dtypes

IDpol            int64
ClaimAmount    float64
dtype: object

In [40]:
freq.select_dtypes(include="number").columns

Index(['IDpol', 'ClaimNb', 'Exposure', 'VehPower', 'VehAge', 'DrivAge',
       'BonusMalus', 'Density'],
      dtype='object')

In [41]:
sev.select_dtypes(include="number").columns

Index(['IDpol', 'ClaimAmount'], dtype='object')

In [42]:
#check Exposure
(freq["Exposure"]<0).sum()

np.int64(0)

In [43]:
#check Exposure
(freq["Exposure"]==0).sum()

np.int64(0)

In [44]:
#check ClaimNb
(freq["ClaimNb"]<0).sum()

np.int64(0)

In [45]:
#check DrivAge
(freq["DrivAge"]<18).sum()

np.int64(0)

In [46]:
freq["DrivAge"].describe()

count    677991.000000
mean         45.499092
std          14.137449
min          18.000000
25%          34.000000
50%          44.000000
75%          55.000000
max         100.000000
Name: DrivAge, dtype: float64

In [47]:
#check VehAge
(freq["VehAge"]<0).sum()

np.int64(0)

In [48]:
#check VehAge
freq["VehAge"].describe()

count    677991.000000
mean          7.044244
std           5.666226
min           0.000000
25%           2.000000
50%           6.000000
75%          11.000000
max         100.000000
Name: VehAge, dtype: float64

In [49]:
# check ClaimAmount
(sev["ClaimAmount"]<0).sum()

np.int64(0)

In [50]:
sev["ClaimAmount"].describe()

count    2.644400e+04
mean     2.265513e+03
std      2.937103e+04
min      1.000000e+00
25%      6.859925e+02
50%      1.172000e+03
75%      1.212385e+03
max      4.075401e+06
Name: ClaimAmount, dtype: float64

In [51]:
sev_claims= sev.groupby("IDpol").size()
sev_claims.describe()

count    24944.000000
mean         1.060135
std          0.289868
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         16.000000
dtype: float64

In [52]:
sev_claims.head()

IDpol
139    1
190    1
414    1
424    2
463    1
dtype: int64

In [53]:
print("FREQUENCY")
print("=" * 50)

print("Shape:", freq.shape)
print("Duplicate rows:", freq.duplicated().sum())
print("Duplicate IDpol:", freq["IDpol"].duplicated().sum())
print("Missing values:")
print(freq.isnull().sum())

print("\nSEVERITY")
print("=" * 50)

print("Shape:", sev.shape)
print("Duplicate rows:", sev.duplicated().sum())
print("Duplicate IDpol:", sev["IDpol"].duplicated().sum())
print("Missing values:")
print(sev.isnull().sum())

FREQUENCY
==================================================
Shape: (677991, 12)
Duplicate rows: 0
Duplicate IDpol: 0
Missing values:
IDpol         0
ClaimNb       0
Exposure      0
VehPower      0
VehAge        0
DrivAge       0
BonusMalus    0
VehBrand      0
VehGas        0
Area          0
Density       0
Region        0
dtype: int64

SEVERITY
==================================================
Shape: (26444, 2)
Duplicate rows: 235
Duplicate IDpol: 1500
Missing values:
IDpol          0
ClaimAmount    0
dtype: int64

In [54]:
print("Exposure < 0:", (freq["Exposure"] < 0).sum())
print("Exposure == 0:", (freq["Exposure"] == 0).sum())
print("Exposure > 1:", (freq["Exposure"] > 1).sum())

print("ClaimNb < 0:", (freq["ClaimNb"] < 0).sum())

print("VehAge < 0:", (freq["VehAge"] < 0).sum())

print("DrivAge < 18:", (freq["DrivAge"] < 18).sum())

print("BonusMalus < 50:", (freq["BonusMalus"] < 50).sum())
print("BonusMalus > 350:", (freq["BonusMalus"] > 350).sum())

print("Density < 0:", (freq["Density"] < 0).sum())

print("ClaimAmount < 0:", (sev["ClaimAmount"] < 0).sum())

print("ClaimAmount == 0:", (sev["ClaimAmount"] == 0).sum())

Exposure < 0: 0
Exposure == 0: 0
Exposure > 1: 1224
ClaimNb < 0: 0
VehAge < 0: 0
DrivAge < 18: 0
BonusMalus < 50: 0
BonusMalus > 350: 0
Density < 0: 0
ClaimAmount < 0: 0
ClaimAmount == 0: 0

In [55]:
print("Area:")
print(freq["Area"].value_counts().sort_index())

print("\nVehGas:")
print(freq["VehGas"].value_counts())

print("\nVehBrand:")
print(freq["VehBrand"].value_counts().sort_index())

print("\nRegion:")
print(freq["Region"].value_counts().sort_index())

Area:
Area
A    103952
B     75457
C    191874
D    151592
E    137163
F     17953
Name: count, dtype: int64

VehGas:
VehGas
Regular    345863
Diesel     332128
Name: count, dtype: int64

VehBrand:
VehBrand
B1     162730
B10     17707
B11     13585
B12    166022
B13     12177
B14      4047
B2     159854
B3      53393
B4      25179
B5      34752
B6      28545
Name: count, dtype: int64

Region:
Region
Alsace                           2200
Aquitaine                       31329
Auvergne                         5287
Basse-Normandie                 10892
Bourgogne                       10491
Bretagne                        42120
Centre                         160595
Champagne-Ardenne                3025
Corse                            4516
Franche-Comte                    1326
Haute-Normandie                  8784
Ile-de-France                   69789
Languedoc-Roussillon            35805
Limousin                         4567
Lorraine                        12990
Midi-Pyrenees                   17141
Nord-Pas-de-Calais              27284
Pays-de-la-Loire                38747
Picardie                         7994
Poitou-Charentes                19046
Provence-Alpes-Cotes-D'Azur     79315
Rhone-Alpes                     84748
Name: count, dtype: int64

In [56]:
sev_claims = sev.groupby("IDpol").size()

In [57]:
severity_counts = (
    sev.groupby("IDpol")
       .size()
       .reset_index(name="SeverityClaimCount")
)

check = freq[["IDpol", "ClaimNb"]].merge(
    severity_counts,
    on="IDpol",
    how="left"
)

check["SeverityClaimCount"] = check["SeverityClaimCount"].fillna(0)

check["Difference"] = (
    check["ClaimNb"] - check["SeverityClaimCount"]
)

check.head()

   IDpol  ClaimNb  SeverityClaimCount  Difference
0    1.0        0                 0.0         0.0
1    3.0        0                 0.0         0.0
2    5.0        0                 0.0         0.0
3   10.0        0                 0.0         0.0
4   11.0        0                 0.0         0.0

In [58]:
check["Difference"].value_counts().sort_index()

Difference
0.0    677991
Name: count, dtype: int64

In [59]:
check[check["Difference"] != 0].head(20)

Empty DataFrame
Columns: [IDpol, ClaimNb, SeverityClaimCount, Difference]
Index: []

In [60]:
(check["Difference"] != 0).sum()

np.int64(0)

In [61]:
severity_count = (
    sev.groupby("IDpol")
       .size()
       .reset_index(name="SeverityClaimCount")
)

freq_check = freq.merge(
    severity_count,
    on="IDpol",
    how="left"
)

freq_check["SeverityClaimCount"] = (
    freq_check["SeverityClaimCount"]
    .fillna(0)
    .astype(int)
)

freq_check["Difference"] = (
    freq_check["ClaimNb"]
    - freq_check["SeverityClaimCount"]
)

print("Frequency rows:", len(freq))
print("Frequency check rows:", len(freq_check))
print("Different policies:", (freq_check["Difference"] != 0).sum())
print("Difference values:")
print(freq_check["Difference"].value_counts().sort_index())

Frequency rows: 677991
Frequency check rows: 677991
Different policies: 0
Difference values:
Difference
0    677991
Name: count, dtype: int64

In [62]:
claim_summary = (
    sev.groupby("IDpol")
       .agg(
           ClaimCount_Severity=("ClaimAmount", "size"),
           TotalClaimCost=("ClaimAmount", "sum"),
           AverageClaimSeverity=("ClaimAmount", "mean"),
           MaxClaimAmount=("ClaimAmount", "max")
       )
       .reset_index()
)

claim_summary.head()

,IDpol,ClaimCount_Severity,TotalClaimCost,AverageClaimSeverity,MaxClaimAmount
0,139,1,303.00,303.00,303.00
1,190,1,1981.84,1981.84,1981.84
2,414,1,1456.55,1456.55,1456.55
3,424,2,10834.00,5417.00,9844.36
4,463,1,3986.67,3986.67,3986.67

In [63]:
print("Number of policies in claim summary:")
print(claim_summary["IDpol"].nunique())

print("Number of rows:")
print(len(claim_summary))

Number of policies in claim summary:
24944
Number of rows:
24944

In [64]:
df = freq.merge(
    claim_summary,
    on="IDpol",
    how="left"
)

print("freq rows:", len(freq))
print("merged rows:", len(df))

freq rows: 677991
merged rows: 677991

In [65]:
df["ClaimCount_Severity"] = (
    df["ClaimCount_Severity"]
    .fillna(0)
    .astype(int)
)

df["TotalClaimCost"] = (
    df["TotalClaimCost"]
    .fillna(0)
)

df["AverageClaimSeverity"] = (
    df["AverageClaimSeverity"]
    .fillna(0)
)

df["MaxClaimAmount"] = (
    df["MaxClaimAmount"]
    .fillna(0)
)

In [66]:
print("Original frequency rows:", len(freq))
print("Final dataframe rows:", len(df))

print(
    "Original unique policies:",
    freq["IDpol"].nunique()
)

print(
    "Final unique policies:",
    df["IDpol"].nunique()
)

Original frequency rows: 677991
Final dataframe rows: 677991
Original unique policies: 677991
Final unique policies: 677991

In [67]:
assert len(df) == len(freq)
assert df["IDpol"].nunique() == freq["IDpol"].nunique()

print("MERGE CHECK: PASSED")

MERGE CHECK: PASSED

In [68]:
policy_count = df["IDpol"].nunique()

In [69]:
total_exposure = df["Exposure"].sum()

In [70]:
total_claim_count = df["ClaimNb"].sum()

In [71]:
claim_frequency = (
    total_claim_count /
    total_exposure
)

In [72]:
total_claim_cost = sev["ClaimAmount"].sum()

In [73]:
average_claim_severity = (
    sev["ClaimAmount"].mean()
)

In [74]:
print("Policy Count:", policy_count)
print("Total Exposure:", total_exposure)
print("Total Claim Count:", total_claim_count)
print("Claim Frequency:", claim_frequency)
print("Total Claim Cost:", total_claim_cost)
print("Average Claim Severity:", average_claim_severity)

Policy Count: 677991
Total Exposure: 358482.8354629838
Total Claim Count: 26444
Claim Frequency: 0.07376643282194344
Total Claim Cost: 59909216.5
Average Claim Severity: 2265.5126493722582

In [75]:
kpi = pd.DataFrame({
    "KPI": [
        "Policy Count",
        "Total Exposure",
        "Total Claim Count",
        "Claim Frequency",
        "Total Claim Cost",
        "Average Claim Severity"
    ],
    "Value": [
        policy_count,
        total_exposure,
        total_claim_count,
        claim_frequency,
        total_claim_cost,
        average_claim_severity
    ]
})

kpi

                      KPI         Value
0            Policy Count  6.779910e+05
1          Total Exposure  3.584828e+05
2       Total Claim Count  2.644400e+04
3         Claim Frequency  7.376643e-02
4        Total Claim Cost  5.990922e+07
5  Average Claim Severity  2.265513e+03

In [76]:
region_analysis = (
    df.groupby("Region")
      .agg(
          PolicyCount=("IDpol", "nunique"),
          Exposure=("Exposure", "sum"),
          ClaimCount=("ClaimNb", "sum"),
          TotalClaimCost=("TotalClaimCost", "sum")
      )
      .reset_index()
)

In [77]:
region_analysis["ClaimFrequency"] = (
    region_analysis["ClaimCount"] /
    region_analysis["Exposure"]
)

In [78]:
region_analysis["AverageSeverity"] = np.where(
    region_analysis["ClaimCount"] > 0,
    region_analysis["TotalClaimCost"] /
    region_analysis["ClaimCount"],
    0
)

In [79]:
region_analysis

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983

In [80]:
region_analysis.sort_values(
    "ClaimFrequency",
    ascending=False
)

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699

In [81]:
region_analysis.sort_values(
    "AverageSeverity",
    ascending=False
)

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028

In [82]:
region_analysis.sort_values(
    "TotalClaimCost",
    ascending=False
)

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526

In [83]:
df["DriverAgeGroup"] = pd.cut(
    df["DrivAge"],
    bins=[17, 25, 35, 45, 55, 65, 100],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56-65",
        "66+"
    ]
)

In [84]:
age_analysis = (
    df.groupby("DriverAgeGroup", observed=True)
      .agg(
          PolicyCount=("IDpol", "nunique"),
          Exposure=("Exposure", "sum"),
          ClaimCount=("ClaimNb", "sum"),
          TotalClaimCost=("TotalClaimCost", "sum")
      )
      .reset_index()
)

In [85]:
age_analysis["ClaimFrequency"] = (
    age_analysis["ClaimCount"] /
    age_analysis["Exposure"]
)

age_analysis["AverageSeverity"] = np.where(
    age_analysis["ClaimCount"] > 0,
    age_analysis["TotalClaimCost"] /
    age_analysis["ClaimCount"],
    0
)

age_analysis

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612
1,26-35,149180,69265.528075,5167,10607248.80,0.074597,2052.883453
2,36-45,170345,87695.996287,6315,12119011.84,0.072010,1919.083427
3,46-55,161895,89265.746408,6622,12326494.29,0.074183,1861.445831
4,56-65,90687,51772.833261,3316,6267615.63,0.064049,1890.113278
5,66+,66991,44256.618168,2621,6281584.40,0.059223,2396.636551

In [86]:
df["VehicleAgeGroup"] = pd.cut(
    df["VehAge"],
    bins=[-1, 5, 10, 15, 100],
    labels=[
        "0-5",
        "6-10",
        "11-15",
        "16+"
    ]
)

In [87]:
vehicle_age_analysis = (
    df.groupby("VehicleAgeGroup", observed=True)
      .agg(
          PolicyCount=("IDpol", "nunique"),
          Exposure=("Exposure", "sum"),
          ClaimCount=("ClaimNb", "sum"),
          TotalClaimCost=("TotalClaimCost", "sum")
      )
      .reset_index()
)

vehicle_age_analysis["ClaimFrequency"] = (
    vehicle_age_analysis["ClaimCount"] /
    vehicle_age_analysis["Exposure"]
)

vehicle_age_analysis["AverageSeverity"] = np.where(
    vehicle_age_analysis["ClaimCount"] > 0,
    vehicle_age_analysis["TotalClaimCost"] /
    vehicle_age_analysis["ClaimCount"],
    0
)

vehicle_age_analysis

,VehicleAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,0-5,320628,151209.259124,11091,22852561.57,0.073349,2060.459974
1,6-10,171587,99003.236361,8009,15805071.87,0.080896,1973.413893
2,11-15,134059,77987.995407,5680,17808346.08,0.072832,3135.272197
3,16+,51717,30282.344571,1664,3443236.98,0.054950,2069.252993

In [88]:
fuel_analysis = (
    df.groupby("VehGas")
      .agg(
          PolicyCount=("IDpol", "nunique"),
          Exposure=("Exposure", "sum"),
          ClaimCount=("ClaimNb", "sum"),
          TotalClaimCost=("TotalClaimCost", "sum")
      )
      .reset_index()
)

fuel_analysis["ClaimFrequency"] = (
    fuel_analysis["ClaimCount"] /
    fuel_analysis["Exposure"]
)

fuel_analysis["AverageSeverity"] = np.where(
    fuel_analysis["ClaimCount"] > 0,
    fuel_analysis["TotalClaimCost"] /
    fuel_analysis["ClaimCount"],
    0
)

fuel_analysis

,VehGas,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,Diesel,332128,170653.973127,13450,27594673.95,0.078814,2051.648621
1,Regular,345863,187828.862336,12994,32314542.55,0.069180,2486.881834

In [89]:
# Pareto Analysis
pareto = (
    sev[["IDpol", "ClaimAmount"]]
    .sort_values(
        "ClaimAmount",
        ascending=False
    )
    .reset_index(drop=True)
)

In [90]:
pareto["CumulativeCost"] = (
    pareto["ClaimAmount"].cumsum()
)

pareto["CumulativePercent"] = (
    pareto["CumulativeCost"] /
    pareto["ClaimAmount"].sum()
) * 100

In [91]:
n1 = max(1, int(len(pareto) * 0.01))

top1_share = (
    pareto.iloc[:n1]["ClaimAmount"].sum()
    /
    pareto["ClaimAmount"].sum()
) * 100

print(
    f"Top 1% share of total claim cost: {top1_share:.2f}%"
)

Top 1% share of total claim cost: 37.99%

In [92]:
n5 = max(1, int(len(pareto) * 0.05))

top5_share = (
    pareto.iloc[:n5]["ClaimAmount"].sum()
    /
    pareto["ClaimAmount"].sum()
) * 100

print(
    f"Top 5% share of total claim cost: {top5_share:.2f}%"
)

Top 5% share of total claim cost: 52.09%

In [93]:
Q1 = sev["ClaimAmount"].quantile(0.25)
Q3 = sev["ClaimAmount"].quantile(0.75)

IQR = Q3 - Q1

upper_bound = Q3 + 1.5 * IQR

outliers = sev[
    sev["ClaimAmount"] > upper_bound
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Upper Bound:", upper_bound)
print("Number of outliers:", len(outliers))

Q1: 685.9925
Q3: 1212.385
IQR: 526.3925
Upper Bound: 2001.97375
Number of outliers: 3842

In [94]:
sev.nlargest(
    20,
    "ClaimAmount"
)

         IDpol  ClaimAmount
9756   1120377   4075400.56
15768   110846   1403057.40
11637  2141337   1301172.60
17992  3122016    774411.50
2869   2008127    390742.27
3307   3025890    369131.88
9999   1117644    307096.42
5521    158309    301635.49
18627  3075820    287423.00
18295  3150210    281897.49
20347  4169019    276643.00
7945   1096763    255013.03
13855  2206511    241171.16
22846  4159792    211204.00
19831  3103319    209695.87
17254  3059946    208472.60
6837   1067220    205432.05
12437  2070262    205132.00
14111  2202813    203172.00
1088   5033465    200885.00

In [95]:
claim_summary = (
    sev.groupby("IDpol")
       .agg(
           ClaimCount_Severity=("ClaimAmount", "size"),
           TotalClaimCost=("ClaimAmount", "sum"),
           AverageClaimSeverity=("ClaimAmount", "mean"),
           MaxClaimAmount=("ClaimAmount", "max")
       )
       .reset_index()
)

df = freq.merge(
    claim_summary,
    on="IDpol",
    how="left"
)

df["ClaimCount_Severity"] = (
    df["ClaimCount_Severity"].fillna(0).astype(int)
)

df["TotalClaimCost"] = df["TotalClaimCost"].fillna(0)
df["AverageClaimSeverity"] = df["AverageClaimSeverity"].fillna(0)
df["MaxClaimAmount"] = df["MaxClaimAmount"].fillna(0)

print("freq rows:", len(freq))
print("df rows:", len(df))
print("freq unique IDpol:", freq["IDpol"].nunique())
print("df unique IDpol:", df["IDpol"].nunique())

freq rows: 677991
df rows: 677991
freq unique IDpol: 677991
df unique IDpol: 677991

In [96]:
# Final Data Quality
df.isnull().sum()

IDpol                   0
ClaimNb                 0
Exposure                0
VehPower                0
VehAge                  0
DrivAge                 0
BonusMalus              0
VehBrand                0
VehGas                  0
Area                    0
Density                 0
Region                  0
ClaimCount_Severity     0
TotalClaimCost          0
AverageClaimSeverity    0
MaxClaimAmount          0
dtype: int64

In [97]:
(df.isnull().mean() * 100).sort_values(ascending=False)

IDpol                   0.0
ClaimNb                 0.0
Exposure                0.0
VehPower                0.0
VehAge                  0.0
DrivAge                 0.0
BonusMalus              0.0
VehBrand                0.0
VehGas                  0.0
Area                    0.0
Density                 0.0
Region                  0.0
ClaimCount_Severity     0.0
TotalClaimCost          0.0
AverageClaimSeverity    0.0
MaxClaimAmount          0.0
dtype: float64

In [98]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate IDpol:", df["IDpol"].duplicated().sum())

Duplicate rows: 0
Duplicate IDpol: 0

In [99]:
#Exposure
print("Exposure < 0:", (df["Exposure"] < 0).sum())
print("Exposure = 0:", (df["Exposure"] == 0).sum())

Exposure < 0: 0
Exposure = 0: 0

In [100]:
#ClaimNb
print("ClaimNb < 0:", (df["ClaimNb"] < 0).sum())

ClaimNb < 0: 0

In [101]:
#Driver Age
print("DrivAge < 18:", (df["DrivAge"] < 18).sum())
print("DrivAge > 100:", (df["DrivAge"] > 100).sum())

DrivAge < 18: 0
DrivAge > 100: 0

In [102]:
#Vehicle Age
print("VehAge < 0:", (df["VehAge"] < 0).sum())

VehAge < 0: 0

In [103]:
#Claim Amount
print("ClaimAmount < 0:", (df["TotalClaimCost"] < 0).sum())

ClaimAmount < 0: 0

In [104]:
zero_exposure = df[df["Exposure"] == 0].copy()

print("Policies with zero exposure:", len(zero_exposure))

Policies with zero exposure: 0

In [105]:
#KPI
policy_count = df["IDpol"].nunique()

total_exposure = df["Exposure"].sum()

total_claim_count = df["ClaimNb"].sum()

total_claim_cost = df["TotalClaimCost"].sum()

claim_frequency = (
    total_claim_count /
    total_exposure
)

average_claim_severity = np.where(
    total_claim_count > 0,
    total_claim_cost / total_claim_count,
    0
)

In [106]:
print("Policy Count:", policy_count)
print("Total Exposure:", total_exposure)
print("Total Claim Count:", total_claim_count)
print("Total Claim Cost:", total_claim_cost)
print("Claim Frequency:", claim_frequency)
print("Average Claim Severity:", average_claim_severity)

Policy Count: 677991
Total Exposure: 358482.8354629838
Total Claim Count: 26444
Total Claim Cost: 59909216.5
Claim Frequency: 0.07376643282194344
Average Claim Severity: 2265.5126493722582

In [107]:
kpi = pd.DataFrame({
    "KPI": [
        "Policy Count",
        "Total Exposure",
        "Claim Count",
        "Claim Frequency",
        "Total Claim Cost",
        "Average Claim Severity"
    ],
    "Value": [
        policy_count,
        total_exposure,
        total_claim_count,
        claim_frequency,
        total_claim_cost,
        average_claim_severity
    ]
})

kpi

                      KPI               Value
0            Policy Count              677991
1          Total Exposure       358482.835463
2             Claim Count               26444
3         Claim Frequency            0.073766
4        Total Claim Cost          59909216.5
5  Average Claim Severity  2265.5126493722582

In [108]:
#Q2: Region Analysis
region_analysis = (
    df.groupby("Region")
      .agg(
          PolicyCount=("IDpol", "nunique"),
          Exposure=("Exposure", "sum"),
          ClaimCount=("ClaimNb", "sum"),
          TotalClaimCost=("TotalClaimCost", "sum")
      )
      .reset_index()
)

region_analysis["ClaimFrequency"] = (
    region_analysis["ClaimCount"] /
    region_analysis["Exposure"]
)

region_analysis["AverageSeverity"] = np.where(
    region_analysis["ClaimCount"] > 0,
    region_analysis["TotalClaimCost"] /
    region_analysis["ClaimCount"],
    0
)

region_analysis

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983

In [109]:
region_analysis.sort_values(
    "ClaimFrequency",
    ascending=False
)

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699

In [110]:
region_analysis.sort_values(
    "AverageSeverity",
    ascending=False
)

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028

In [111]:
region_analysis.sort_values(
    "TotalClaimCost",
    ascending=False
)

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526

In [112]:
region_analysis

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983

In [113]:
#ساخت جدول رتبه بندی برای tableau
region_rank = region_analysis.copy()

region_rank["FrequencyRank"] = (
    region_rank["ClaimFrequency"]
    .rank(method="min", ascending=False)
)

region_rank["SeverityRank"] = (
    region_rank["AverageSeverity"]
    .rank(method="min", ascending=False)
)

region_rank["CostRank"] = (
    region_rank["TotalClaimCost"]
    .rank(method="min", ascending=False)
)

region_rank = region_rank.sort_values(
    "FrequencyRank"
)

region_rank

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyRank,SeverityRank,CostRank
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983,1.0,4.0,2.0
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121,2.0,7.0,13.0
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729,3.0,14.0,4.0
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973,4.0,5.0,3.0
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208,5.0,20.0,19.0
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839,6.0,15.0,9.0
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848,7.0,21.0,21.0
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773,8.0,2.0,17.0
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062,9.0,13.0,8.0
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135,10.0,11.0,7.0
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925,11.0,17.0,6.0
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725,12.0,16.0,10.0
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182,13.0,18.0,18.0
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145,14.0,12.0,14.0
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314,15.0,9.0,12.0
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685,16.0,8.0,5.0
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526,17.0,10.0,22.0
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442,18.0,1.0,16.0
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422,19.0,3.0,1.0
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028,20.0,22.0,20.0
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513,21.0,6.0,11.0
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699,22.0,19.0,15.0

In [114]:
region_rank[
    [
        "Region",
        "PolicyCount",
        "Exposure",
        "ClaimCount",
        "TotalClaimCost",
        "ClaimFrequency",
        "AverageSeverity",
        "FrequencyRank",
        "SeverityRank",
        "CostRank"
    ]
]

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyRank,SeverityRank,CostRank
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983,1.0,4.0,2.0
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121,2.0,7.0,13.0
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729,3.0,14.0,4.0
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973,4.0,5.0,3.0
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208,5.0,20.0,19.0
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839,6.0,15.0,9.0
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848,7.0,21.0,21.0
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773,8.0,2.0,17.0
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062,9.0,13.0,8.0
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135,10.0,11.0,7.0
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925,11.0,17.0,6.0
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725,12.0,16.0,10.0
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182,13.0,18.0,18.0
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145,14.0,12.0,14.0
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314,15.0,9.0,12.0
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685,16.0,8.0,5.0
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526,17.0,10.0,22.0
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442,18.0,1.0,16.0
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422,19.0,3.0,1.0
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028,20.0,22.0,20.0
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513,21.0,6.0,11.0
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699,22.0,19.0,15.0

In [115]:
#Q3:
print(df["DrivAge"].describe())
print(df["VehAge"].describe())
print(df["VehPower"].describe())
print(df["BonusMalus"].describe())

count    677991.000000
mean         45.499092
std          14.137449
min          18.000000
25%          34.000000
50%          44.000000
75%          55.000000
max         100.000000
Name: DrivAge, dtype: float64
count    677991.000000
mean          7.044244
std           5.666226
min           0.000000
25%           2.000000
50%           6.000000
75%          11.000000
max         100.000000
Name: VehAge, dtype: float64
count    677991.000000
mean          6.454649
std           2.050914
min           4.000000
25%           5.000000
50%           6.000000
75%           7.000000
max          15.000000
Name: VehPower, dtype: float64
count    677991.000000
mean         59.761559
std          15.636713
min          50.000000
25%          50.000000
50%          50.000000
75%          64.000000
max         230.000000
Name: BonusMalus, dtype: float64

In [116]:
print(df["VehGas"].value_counts(dropna=False))

VehGas
Regular    345863
Diesel     332128
Name: count, dtype: int64

In [117]:
print("VehAge = 100:")
print((df["VehAge"] == 100).sum())

VehAge = 100:
25

In [118]:
print(
    df[df["VehAge"] == 100][
        ["IDpol", "VehAge", "DrivAge", "VehPower", "BonusMalus", "VehGas"]
    ].head(20)
)

            IDpol  VehAge  DrivAge  VehPower  BonusMalus   VehGas
20637     45432.0     100       32         4          68  Regular
23866     51259.0     100       42         5          50   Diesel
26016     55270.0     100       30         8          72   Diesel
131012  1087165.0     100       24         7          72   Diesel
131046  1087251.0     100       53         7          50  Regular
131097  1087352.0     100       20         9         100  Regular
131098  1087353.0     100       20         9          90  Regular
142995  1109849.0     100       57         7          60  Regular
145416  1113718.0     100       46         4          50  Regular
156811  1130132.0     100       75         6          55  Regular
157919  1132516.0     100       38         6          50   Diesel
160158  1137310.0     100       34         4          50  Regular
160941  1138982.0     100       33         7          54  Regular
163607  1144784.0     100       42         7         106  Regular
164044  1145735.0     100       40         7          64   Diesel
165833  1149648.0     100       52         6          50  Regular
167581  1153624.0     100       31         5          76   Diesel
169213  1157330.0     100       54         7          57   Diesel
169256  1157433.0     100       36         6          90   Diesel
169257  1157434.0     100       36         6          85   Diesel

In [119]:
df["VehPower"].value_counts().sort_index()

VehPower
4     115344
5     124815
6     148972
7     145398
8      46954
9      30084
10     31353
11     18352
12      8214
13      3229
14      2350
15      2926
Name: count, dtype: int64

In [120]:
df["BonusMalus"].value_counts().sort_index().head(30)

BonusMalus
50    384142
51     15869
52      4770
53      3351
54     17359
55      5593
56      3453
57     17937
58      5969
59      2779
60     17363
61      1724
62      7180
63      3169
64     18192
65      1533
66      1348
67      2782
68     18790
69      1097
70      1113
71      2056
72     18580
73       985
74       670
75      1345
76     18226
77       983
78       641
79       253
Name: count, dtype: int64

In [121]:
df["BonusMalus"].value_counts().sort_index().tail(30)

BonusMalus
140    118
141      6
142      4
144      4
147    121
148     63
149      1
151      1
156    139
158      4
162      2
163      1
165     11
166      2
173      7
174      2
175      3
176      3
177      2
183      6
185      5
187      3
190      3
195      6
196      3
198      2
208      1
218      1
228      1
230      1
Name: count, dtype: int64

In [122]:
vehage_100 = df[df["VehAge"] == 100]

print("Number of VehAge = 100:", len(vehage_100))

print("\nTotal Exposure:")
print(vehage_100["Exposure"].sum())

print("\nClaim Count:")
print(vehage_100["ClaimNb"].sum())

print("\nTotal Claim Cost:")
print(vehage_100["TotalClaimCost"].sum())

Number of VehAge = 100: 25

Total Exposure:
15.150000000000002

Claim Count:
0

Total Claim Cost:
0.0

In [123]:
print(
    vehage_100[
        [
            "IDpol",
            "VehAge",
            "DrivAge",
            "VehPower",
            "BonusMalus",
            "VehGas",
            "Exposure",
            "ClaimNb"
        ]
    ].describe()
)

              IDpol  VehAge    DrivAge   VehPower  BonusMalus  Exposure  \
count  2.500000e+01    25.0  25.000000  25.000000   25.000000  25.00000
mean   1.006325e+06   100.0  39.920000   6.160000   65.000000   0.60600
std    3.611819e+05     0.0  12.566225   1.434108   17.255434   0.34907
min    4.543200e+04   100.0  20.000000   4.000000   50.000000   0.01000
25%    1.087353e+06   100.0  32.000000   5.000000   50.000000   0.32000
50%    1.138982e+06   100.0  38.000000   6.000000   57.000000   0.63000
75%    1.157433e+06   100.0  46.000000   7.000000   72.000000   0.96000
max    1.171644e+06   100.0  75.000000   9.000000  106.000000   1.00000

       ClaimNb
count     25.0
mean       0.0
std        0.0
min        0.0
25%        0.0
50%        0.0
75%        0.0
max        0.0

In [124]:
df["DriverAgeGroup"] = pd.cut(
    df["DrivAge"],
    bins=[17, 25, 35, 45, 55, 65, 100],
    labels=[
        "18-25",
        "26-35",
        "36-45",
        "46-55",
        "56-65",
        "66+"
    ]
)

In [125]:
def segment_analysis(data, group_col):
    result = (
        data.groupby(group_col, observed=True)
            .agg(
                PolicyCount=("IDpol", "nunique"),
                Exposure=("Exposure", "sum"),
                ClaimCount=("ClaimNb", "sum"),
                TotalClaimCost=("TotalClaimCost", "sum")
            )
            .reset_index()
    )

    result["ClaimFrequency"] = (
        result["ClaimCount"] /
        result["Exposure"]
    )

    result["AverageSeverity"] = np.where(
        result["ClaimCount"] > 0,
        result["TotalClaimCost"] /
        result["ClaimCount"],
        0
    )

    return result

In [126]:
age_analysis = segment_analysis(
    df,
    "DriverAgeGroup"
)

age_analysis

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612
1,26-35,149180,69265.528075,5167,10607248.80,0.074597,2052.883453
2,36-45,170345,87695.996287,6315,12119011.84,0.072010,1919.083427
3,46-55,161895,89265.746408,6622,12326494.29,0.074183,1861.445831
4,56-65,90687,51772.833261,3316,6267615.63,0.064049,1890.113278
5,66+,66991,44256.618168,2621,6281584.40,0.059223,2396.636551

In [127]:
age_analysis.sort_values(
    "ClaimFrequency",
    ascending=False
)

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612
1,26-35,149180,69265.528075,5167,10607248.80,0.074597,2052.883453
3,46-55,161895,89265.746408,6622,12326494.29,0.074183,1861.445831
2,36-45,170345,87695.996287,6315,12119011.84,0.072010,1919.083427
4,56-65,90687,51772.833261,3316,6267615.63,0.064049,1890.113278
5,66+,66991,44256.618168,2621,6281584.40,0.059223,2396.636551

In [128]:
age_analysis.sort_values(
    "AverageSeverity",
    ascending=False
)

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612
5,66+,66991,44256.618168,2621,6281584.40,0.059223,2396.636551
1,26-35,149180,69265.528075,5167,10607248.80,0.074597,2052.883453
2,36-45,170345,87695.996287,6315,12119011.84,0.072010,1919.083427
4,56-65,90687,51772.833261,3316,6267615.63,0.064049,1890.113278
3,46-55,161895,89265.746408,6622,12326494.29,0.074183,1861.445831

In [129]:
df["VehicleAgeGroup"] = pd.cut(
    df["VehAge"],
    bins=[-1, 2, 5, 10, 15, 100],
    labels=[
        "0-2",
        "3-5",
        "6-10",
        "11-15",
        "16+"
    ]
)

In [130]:
vehicle_age_analysis = segment_analysis(
    df,
    "VehicleAgeGroup"
)

vehicle_age_analysis

,VehicleAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,0-2,188140,79171.135348,5747,12299662.34,0.072590,2140.188331
1,3-5,132488,72038.123776,5344,10552899.23,0.074183,1974.719167
2,6-10,171587,99003.236361,8009,15805071.87,0.080896,1973.413893
3,11-15,134059,77987.995407,5680,17808346.08,0.072832,3135.272197
4,16+,51717,30282.344571,1664,3443236.98,0.054950,2069.252993

In [131]:
vehicle_age_analysis.sort_values(
    "ClaimFrequency",
    ascending=False
)

,VehicleAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
2,6-10,171587,99003.236361,8009,15805071.87,0.080896,1973.413893
1,3-5,132488,72038.123776,5344,10552899.23,0.074183,1974.719167
3,11-15,134059,77987.995407,5680,17808346.08,0.072832,3135.272197
0,0-2,188140,79171.135348,5747,12299662.34,0.072590,2140.188331
4,16+,51717,30282.344571,1664,3443236.98,0.054950,2069.252993

In [132]:
vehicle_age_analysis.sort_values(
    "AverageSeverity",
    ascending=False
)

,VehicleAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
3,11-15,134059,77987.995407,5680,17808346.08,0.072832,3135.272197
0,0-2,188140,79171.135348,5747,12299662.34,0.072590,2140.188331
4,16+,51717,30282.344571,1664,3443236.98,0.054950,2069.252993
1,3-5,132488,72038.123776,5344,10552899.23,0.074183,1974.719167
2,6-10,171587,99003.236361,8009,15805071.87,0.080896,1973.413893

In [133]:
power_analysis = segment_analysis(
    df,
    "VehPower"
)

power_analysis

,VehPower,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,4,115344,60069.707304,4003,9410083.43,0.066639,2350.757789
1,5,124815,68168.818821,5115,8837747.14,0.075034,1727.809803
2,6,148972,82520.440172,6305,14385946.83,0.076405,2281.672772
3,7,145398,77948.436700,5593,12426397.16,0.071753,2221.776714
4,8,46954,22682.946305,1645,2954665.51,0.072521,1796.149246
5,9,30084,15348.113656,1220,6265052.65,0.079489,5135.289057
6,10,31353,15374.420824,1217,2853312.33,0.079157,2344.545875
7,11,18352,8497.778452,714,1312132.16,0.084022,1837.720112
8,12,8214,3792.038343,296,707682.28,0.078058,2390.818514
9,13,3229,1637.255322,139,310503.58,0.084898,2233.838705
10,14,2350,1182.350391,101,321419.99,0.085423,3182.376139
11,15,2926,1260.529173,96,124273.44,0.076158,1294.515000

In [134]:
power_analysis.sort_values(
    "ClaimFrequency",
    ascending=False
)

,VehPower,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
10,14,2350,1182.350391,101,321419.99,0.085423,3182.376139
9,13,3229,1637.255322,139,310503.58,0.084898,2233.838705
7,11,18352,8497.778452,714,1312132.16,0.084022,1837.720112
5,9,30084,15348.113656,1220,6265052.65,0.079489,5135.289057
6,10,31353,15374.420824,1217,2853312.33,0.079157,2344.545875
8,12,8214,3792.038343,296,707682.28,0.078058,2390.818514
2,6,148972,82520.440172,6305,14385946.83,0.076405,2281.672772
11,15,2926,1260.529173,96,124273.44,0.076158,1294.515000
1,5,124815,68168.818821,5115,8837747.14,0.075034,1727.809803
4,8,46954,22682.946305,1645,2954665.51,0.072521,1796.149246
3,7,145398,77948.436700,5593,12426397.16,0.071753,2221.776714
0,4,115344,60069.707304,4003,9410083.43,0.066639,2350.757789

In [135]:
power_analysis.sort_values(
    "AverageSeverity",
    ascending=False
)

,VehPower,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
5,9,30084,15348.113656,1220,6265052.65,0.079489,5135.289057
10,14,2350,1182.350391,101,321419.99,0.085423,3182.376139
8,12,8214,3792.038343,296,707682.28,0.078058,2390.818514
0,4,115344,60069.707304,4003,9410083.43,0.066639,2350.757789
6,10,31353,15374.420824,1217,2853312.33,0.079157,2344.545875
2,6,148972,82520.440172,6305,14385946.83,0.076405,2281.672772
9,13,3229,1637.255322,139,310503.58,0.084898,2233.838705
3,7,145398,77948.436700,5593,12426397.16,0.071753,2221.776714
7,11,18352,8497.778452,714,1312132.16,0.084022,1837.720112
4,8,46954,22682.946305,1645,2954665.51,0.072521,1796.149246
1,5,124815,68168.818821,5115,8837747.14,0.075034,1727.809803
11,15,2926,1260.529173,96,124273.44,0.076158,1294.515000

In [136]:
df["BonusMalus"].value_counts().sort_index()

BonusMalus
50     384142
51      15869
52       4770
53       3351
54      17359
        ...
198         2
208         1
218         1
228         1
230         1
Name: count, Length: 115, dtype: int64

In [137]:
#Fuel Type
fuel_analysis = segment_analysis(
    df,
    "VehGas")

fuel_analysis

,VehGas,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,Diesel,332128,170653.973127,13450,27594673.95,0.078814,2051.648621
1,Regular,345863,187828.862336,12994,32314542.55,0.069180,2486.881834

In [138]:
fuel_analysis.sort_values(
    "ClaimFrequency",
    ascending=False
)

,VehGas,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,Diesel,332128,170653.973127,13450,27594673.95,0.078814,2051.648621
1,Regular,345863,187828.862336,12994,32314542.55,0.069180,2486.881834

In [139]:
fuel_analysis.sort_values(
    "AverageSeverity",
    ascending=False
)

,VehGas,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
1,Regular,345863,187828.862336,12994,32314542.55,0.069180,2486.881834
0,Diesel,332128,170653.973127,13450,27594673.95,0.078814,2051.648621

In [140]:
vehage_100 = df[df["VehAge"] == 100]

print("Number of VehAge = 100:", len(vehage_100))
print("Exposure:", vehage_100["Exposure"].sum())
print("Claim Count:", vehage_100["ClaimNb"].sum())
print("Total Claim Cost:", vehage_100["TotalClaimCost"].sum())

Number of VehAge = 100: 25
Exposure: 15.150000000000002
Claim Count: 0
Total Claim Cost: 0.0

In [141]:
age_analysis = segment_analysis(
    df,
    "DriverAgeGroup"
)

age_analysis

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612
1,26-35,149180,69265.528075,5167,10607248.80,0.074597,2052.883453
2,36-45,170345,87695.996287,6315,12119011.84,0.072010,1919.083427
3,46-55,161895,89265.746408,6622,12326494.29,0.074183,1861.445831
4,56-65,90687,51772.833261,3316,6267615.63,0.064049,1890.113278
5,66+,66991,44256.618168,2621,6281584.40,0.059223,2396.636551

In [142]:
vehicle_age_analysis = segment_analysis(
    df,
    "VehicleAgeGroup"
)

vehicle_age_analysis

,VehicleAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,0-2,188140,79171.135348,5747,12299662.34,0.072590,2140.188331
1,3-5,132488,72038.123776,5344,10552899.23,0.074183,1974.719167
2,6-10,171587,99003.236361,8009,15805071.87,0.080896,1973.413893
3,11-15,134059,77987.995407,5680,17808346.08,0.072832,3135.272197
4,16+,51717,30282.344571,1664,3443236.98,0.054950,2069.252993

In [143]:
power_analysis = segment_analysis(
    df,
    "VehPower"
)

power_analysis

,VehPower,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,4,115344,60069.707304,4003,9410083.43,0.066639,2350.757789
1,5,124815,68168.818821,5115,8837747.14,0.075034,1727.809803
2,6,148972,82520.440172,6305,14385946.83,0.076405,2281.672772
3,7,145398,77948.436700,5593,12426397.16,0.071753,2221.776714
4,8,46954,22682.946305,1645,2954665.51,0.072521,1796.149246
5,9,30084,15348.113656,1220,6265052.65,0.079489,5135.289057
6,10,31353,15374.420824,1217,2853312.33,0.079157,2344.545875
7,11,18352,8497.778452,714,1312132.16,0.084022,1837.720112
8,12,8214,3792.038343,296,707682.28,0.078058,2390.818514
9,13,3229,1637.255322,139,310503.58,0.084898,2233.838705
10,14,2350,1182.350391,101,321419.99,0.085423,3182.376139
11,15,2926,1260.529173,96,124273.44,0.076158,1294.515000

In [144]:
power_analysis.sort_values(
    "ClaimFrequency",
    ascending=False
)

,VehPower,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
10,14,2350,1182.350391,101,321419.99,0.085423,3182.376139
9,13,3229,1637.255322,139,310503.58,0.084898,2233.838705
7,11,18352,8497.778452,714,1312132.16,0.084022,1837.720112
5,9,30084,15348.113656,1220,6265052.65,0.079489,5135.289057
6,10,31353,15374.420824,1217,2853312.33,0.079157,2344.545875
8,12,8214,3792.038343,296,707682.28,0.078058,2390.818514
2,6,148972,82520.440172,6305,14385946.83,0.076405,2281.672772
11,15,2926,1260.529173,96,124273.44,0.076158,1294.515000
1,5,124815,68168.818821,5115,8837747.14,0.075034,1727.809803
4,8,46954,22682.946305,1645,2954665.51,0.072521,1796.149246
3,7,145398,77948.436700,5593,12426397.16,0.071753,2221.776714
0,4,115344,60069.707304,4003,9410083.43,0.066639,2350.757789

In [145]:
power_analysis.sort_values(
    "AverageSeverity",
    ascending=False
)

,VehPower,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
5,9,30084,15348.113656,1220,6265052.65,0.079489,5135.289057
10,14,2350,1182.350391,101,321419.99,0.085423,3182.376139
8,12,8214,3792.038343,296,707682.28,0.078058,2390.818514
0,4,115344,60069.707304,4003,9410083.43,0.066639,2350.757789
6,10,31353,15374.420824,1217,2853312.33,0.079157,2344.545875
2,6,148972,82520.440172,6305,14385946.83,0.076405,2281.672772
9,13,3229,1637.255322,139,310503.58,0.084898,2233.838705
3,7,145398,77948.436700,5593,12426397.16,0.071753,2221.776714
7,11,18352,8497.778452,714,1312132.16,0.084022,1837.720112
4,8,46954,22682.946305,1645,2954665.51,0.072521,1796.149246
1,5,124815,68168.818821,5115,8837747.14,0.075034,1727.809803
11,15,2926,1260.529173,96,124273.44,0.076158,1294.515000

In [146]:
bonus_counts = (
    df["BonusMalus"]
    .value_counts()
    .sort_index()
)

bonus_counts

BonusMalus
50     384142
51      15869
52       4770
53       3351
54      17359
        ...
198         2
208         1
218         1
228         1
230         1
Name: count, Length: 115, dtype: int64

In [147]:
print("BonusMalus = 50:")
print((df["BonusMalus"] == 50).sum())

print("\nPercentage:")
print(round((df["BonusMalus"] == 50).mean() * 100, 2), "%")

print("\nMinimum:", df["BonusMalus"].min())
print("Maximum:", df["BonusMalus"].max())
print("Unique values:", df["BonusMalus"].nunique())

BonusMalus = 50:
384142

Percentage:
56.66 %

Minimum: 50
Maximum: 230
Unique values: 115

In [148]:
#Bonus-Malus
df["BonusMalusGroup"] = pd.cut(
    df["BonusMalus"],
    bins=[49, 50, 60, 70, 80, 90, 100, 120, 230],
    labels=[
        "50",
        "51-60",
        "61-70",
        "71-80",
        "81-90",
        "91-100",
        "101-120",
        "121+"
    ],
    include_lowest=True
)

In [149]:
bonus_analysis = segment_analysis(
    df,
    "BonusMalusGroup"
)

bonus_analysis

,BonusMalusGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,50,384142,225222.490903,11592,22282394.02,0.051469,1922.221706
1,51-60,94443,47983.227013,3576,7025420.41,0.074526,1964.603023
2,61-70,56928,26496.753500,3116,6091205.46,0.117599,1954.815616
3,71-80,61824,26566.663294,2798,6142659.22,0.105320,2195.374989
4,81-90,35724,15246.919478,1720,3657454.13,0.112810,2126.426820
5,91-100,37136,13395.462272,2386,12150153.70,0.178120,5092.268944
6,101-120,5554,2573.003003,800,1568366.06,0.310921,1960.457575
7,121+,2240,998.316000,456,991563.50,0.456769,2174.481360

In [150]:
bonus_analysis.sort_values(
    "ClaimFrequency",
    ascending=False
)

,BonusMalusGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
7,121+,2240,998.316000,456,991563.50,0.456769,2174.481360
6,101-120,5554,2573.003003,800,1568366.06,0.310921,1960.457575
5,91-100,37136,13395.462272,2386,12150153.70,0.178120,5092.268944
2,61-70,56928,26496.753500,3116,6091205.46,0.117599,1954.815616
4,81-90,35724,15246.919478,1720,3657454.13,0.112810,2126.426820
3,71-80,61824,26566.663294,2798,6142659.22,0.105320,2195.374989
1,51-60,94443,47983.227013,3576,7025420.41,0.074526,1964.603023
0,50,384142,225222.490903,11592,22282394.02,0.051469,1922.221706

In [151]:
bonus_analysis.sort_values(
    "AverageSeverity",
    ascending=False
)

,BonusMalusGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
5,91-100,37136,13395.462272,2386,12150153.70,0.178120,5092.268944
3,71-80,61824,26566.663294,2798,6142659.22,0.105320,2195.374989
7,121+,2240,998.316000,456,991563.50,0.456769,2174.481360
4,81-90,35724,15246.919478,1720,3657454.13,0.112810,2126.426820
1,51-60,94443,47983.227013,3576,7025420.41,0.074526,1964.603023
6,101-120,5554,2573.003003,800,1568366.06,0.310921,1960.457575
2,61-70,56928,26496.753500,3116,6091205.46,0.117599,1954.815616
0,50,384142,225222.490903,11592,22282394.02,0.051469,1922.221706

In [152]:
#تعیین Benchmark کل Portfolio
portfolio_frequency = df["ClaimNb"].sum() / df["Exposure"].sum()

portfolio_severity = (
    df["TotalClaimCost"].sum() / df["ClaimNb"].sum()
)

print("Portfolio Frequency:", portfolio_frequency)
print("Portfolio Severity:", portfolio_severity)

Portfolio Frequency: 0.07376643282194344
Portfolio Severity: 2265.5126493722582

In [153]:
bonus_q4 = bonus_analysis.copy()

bonus_q4["FrequencyLevel"] = np.where(
    bonus_q4["ClaimFrequency"] > portfolio_frequency,
    "High Frequency",
    "Low Frequency"
)

bonus_q4["SeverityLevel"] = np.where(
    bonus_q4["AverageSeverity"] > portfolio_severity,
    "High Severity",
    "Low Severity"
)

bonus_q4["RiskQuadrant"] = (
    bonus_q4["FrequencyLevel"]
    + " + "
    + bonus_q4["SeverityLevel"]
)

bonus_q4

,BonusMalusGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant
0,50,384142,225222.490903,11592,22282394.02,0.051469,1922.221706,Low Frequency,Low Severity,Low Frequency + Low Severity
1,51-60,94443,47983.227013,3576,7025420.41,0.074526,1964.603023,High Frequency,Low Severity,High Frequency + Low Severity
2,61-70,56928,26496.753500,3116,6091205.46,0.117599,1954.815616,High Frequency,Low Severity,High Frequency + Low Severity
3,71-80,61824,26566.663294,2798,6142659.22,0.105320,2195.374989,High Frequency,Low Severity,High Frequency + Low Severity
4,81-90,35724,15246.919478,1720,3657454.13,0.112810,2126.426820,High Frequency,Low Severity,High Frequency + Low Severity
5,91-100,37136,13395.462272,2386,12150153.70,0.178120,5092.268944,High Frequency,High Severity,High Frequency + High Severity
6,101-120,5554,2573.003003,800,1568366.06,0.310921,1960.457575,High Frequency,Low Severity,High Frequency + Low Severity
7,121+,2240,998.316000,456,991563.50,0.456769,2174.481360,High Frequency,Low Severity,High Frequency + Low Severity

In [154]:
high_risk_bonus = bonus_q4[
    bonus_q4["RiskQuadrant"] == "High Frequency + High Severity"
]

high_risk_bonus

,BonusMalusGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant
5,91-100,37136,13395.462272,2386,12150153.7,0.17812,5092.268944,High Frequency,High Severity,High Frequency + High Severity

In [155]:
driver_q4 = (
    df.groupby("DriverAgeGroup", observed=True)
    .agg(
        PolicyCount=("IDpol", "count"),
        Exposure=("Exposure", "sum"),
        ClaimCount=("ClaimNb", "sum"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

driver_q4["ClaimFrequency"] = (
    driver_q4["ClaimCount"] / driver_q4["Exposure"]
)

driver_q4["AverageSeverity"] = np.where(
    driver_q4["ClaimCount"] > 0,
    driver_q4["TotalClaimCost"] / driver_q4["ClaimCount"],
    0
)

driver_q4["FrequencyLevel"] = np.where(
    driver_q4["ClaimFrequency"] > portfolio_frequency,
    "High Frequency",
    "Low Frequency"
)

driver_q4["SeverityLevel"] = np.where(
    driver_q4["AverageSeverity"] > portfolio_severity,
    "High Severity",
    "Low Severity"
)

driver_q4["RiskQuadrant"] = (
    driver_q4["FrequencyLevel"]
    + " + "
    + driver_q4["SeverityLevel"]
)

driver_q4

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612,High Frequency,High Severity,High Frequency + High Severity
1,26-35,149180,69265.528075,5167,10607248.80,0.074597,2052.883453,High Frequency,Low Severity,High Frequency + Low Severity
2,36-45,170345,87695.996287,6315,12119011.84,0.072010,1919.083427,Low Frequency,Low Severity,Low Frequency + Low Severity
3,46-55,161895,89265.746408,6622,12326494.29,0.074183,1861.445831,High Frequency,Low Severity,High Frequency + Low Severity
4,56-65,90687,51772.833261,3316,6267615.63,0.064049,1890.113278,Low Frequency,Low Severity,Low Frequency + Low Severity
5,66+,66991,44256.618168,2621,6281584.40,0.059223,2396.636551,Low Frequency,High Severity,Low Frequency + High Severity

In [156]:
high_risk_driver = driver_q4[
    driver_q4["RiskQuadrant"] == "High Frequency + High Severity"
]

high_risk_driver

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612,High Frequency,High Severity,High Frequency + High Severity

In [157]:
driver_q4["RiskQuadrant"].value_counts()

RiskQuadrant
High Frequency + Low Severity     2
Low Frequency + Low Severity      2
High Frequency + High Severity    1
Low Frequency + High Severity     1
Name: count, dtype: int64

In [158]:
risk_summary = (
    driver_q4.groupby("RiskQuadrant", observed=True)
    .agg(
        DriverAgeGroups=("DriverAgeGroup", "count"),
        TotalPolicies=("PolicyCount", "sum"),
        TotalClaims=("ClaimCount", "sum"),
        TotalExposure=("Exposure", "sum"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

risk_summary

,RiskQuadrant,DriverAgeGroups,TotalPolicies,TotalClaims,TotalExposure,TotalClaimCost
0,High Frequency + High Severity,1,38893,2403,16226.113263,12307261.54
1,High Frequency + Low Severity,2,311075,11789,158531.274484,22933743.09
2,Low Frequency + High Severity,1,66991,2621,44256.618168,6281584.40
3,Low Frequency + Low Severity,2,261032,9631,139468.829549,18386627.47

In [159]:
high_risk_driver.sort_values(
    ["ClaimFrequency", "AverageSeverity"],
    ascending=False
)

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612,High Frequency,High Severity,High Frequency + High Severity

In [160]:
high_risk_driver = high_risk_driver.copy()

high_risk_driver["PolicyShare"] = (
    high_risk_driver["PolicyCount"] / df["IDpol"].nunique()
)

high_risk_driver["ClaimShare"] = (
    high_risk_driver["ClaimCount"] / df["ClaimNb"].sum()
)

high_risk_driver

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant,PolicyShare,ClaimShare
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612,High Frequency,High Severity,High Frequency + High Severity,0.057365,0.090871

In [161]:
high_risk_driver["ClaimShare_to_PolicyShare"] = (
    high_risk_driver["ClaimShare"] /
    high_risk_driver["PolicyShare"]
)

high_risk_driver

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant,PolicyShare,ClaimShare,ClaimShare_to_PolicyShare
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612,High Frequency,High Severity,High Frequency + High Severity,0.057365,0.090871,1.584087

In [162]:
df["VehAge"].describe()

count    677991.000000
mean          7.044244
std           5.666226
min           0.000000
25%           2.000000
50%           6.000000
75%          11.000000
max         100.000000
Name: VehAge, dtype: float64

In [163]:
df["VehicleAgeGroup"] = pd.cut(
    df["VehAge"],
    bins=[-1, 2, 5, 10, 15, 20, np.inf],
    labels=[
        "0-2",
        "3-5",
        "6-10",
        "11-15",
        "16-20",
        "21+"
    ]
)

In [164]:
df["VehicleAgeGroup"].value_counts().sort_index()

VehicleAgeGroup
0-2      188140
3-5      132488
6-10     171587
11-15    134059
16-20     43396
21+        8321
Name: count, dtype: int64

In [165]:
vehicle_q4 = (
    df.groupby("VehicleAgeGroup", observed=True)
    .agg(
        PolicyCount=("IDpol", "count"),
        Exposure=("Exposure", "sum"),
        ClaimCount=("ClaimNb", "sum"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

vehicle_q4["ClaimFrequency"] = (
    vehicle_q4["ClaimCount"] / vehicle_q4["Exposure"]
)

vehicle_q4["AverageSeverity"] = np.where(
    vehicle_q4["ClaimCount"] > 0,
    vehicle_q4["TotalClaimCost"] / vehicle_q4["ClaimCount"],
    0
)

In [166]:
vehicle_q4["FrequencyLevel"] = np.where(
    vehicle_q4["ClaimFrequency"] > portfolio_frequency,
    "High Frequency",
    "Low Frequency"
)

vehicle_q4["SeverityLevel"] = np.where(
    vehicle_q4["AverageSeverity"] > portfolio_severity,
    "High Severity",
    "Low Severity"
)

In [167]:
vehicle_q4["RiskQuadrant"] = (
    vehicle_q4["FrequencyLevel"]
    + " + "
    + vehicle_q4["SeverityLevel"]
)

vehicle_q4

,VehicleAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant
0,0-2,188140,79171.135348,5747,12299662.34,0.072590,2140.188331,Low Frequency,Low Severity,Low Frequency + Low Severity
1,3-5,132488,72038.123776,5344,10552899.23,0.074183,1974.719167,High Frequency,Low Severity,High Frequency + Low Severity
2,6-10,171587,99003.236361,8009,15805071.87,0.080896,1973.413893,High Frequency,Low Severity,High Frequency + Low Severity
3,11-15,134059,77987.995407,5680,17808346.08,0.072832,3135.272197,Low Frequency,High Severity,Low Frequency + High Severity
4,16-20,43396,25135.228607,1457,3010392.67,0.057966,2066.158318,Low Frequency,Low Severity,Low Frequency + Low Severity
5,21+,8321,5147.115965,207,432844.31,0.040217,2091.035314,Low Frequency,Low Severity,Low Frequency + Low Severity

In [168]:
high_risk_vehicle = vehicle_q4[
    vehicle_q4["RiskQuadrant"] == "High Frequency + High Severity"
]

high_risk_vehicle

Empty DataFrame
Columns: [VehicleAgeGroup, PolicyCount, Exposure, ClaimCount, TotalClaimCost, ClaimFrequency, AverageSeverity, FrequencyLevel, SeverityLevel, RiskQuadrant]
Index: []

In [169]:
vehicle_q4["RiskQuadrant"].value_counts()

RiskQuadrant
Low Frequency + Low Severity     3
High Frequency + Low Severity    2
Low Frequency + High Severity    1
Name: count, dtype: int64

In [170]:
high_risk_vehicle

Empty DataFrame
Columns: [VehicleAgeGroup, PolicyCount, Exposure, ClaimCount, TotalClaimCost, ClaimFrequency, AverageSeverity, FrequencyLevel, SeverityLevel, RiskQuadrant]
Index: []

In [171]:
vehicle_q4["RiskQuadrant"].value_counts()

RiskQuadrant
Low Frequency + Low Severity     3
High Frequency + Low Severity    2
Low Frequency + High Severity    1
Name: count, dtype: int64

In [172]:
vehicle_q4["PolicyShare"] = (
    vehicle_q4["PolicyCount"] / df["IDpol"].nunique()
)

vehicle_q4["ClaimShare"] = (
    vehicle_q4["ClaimCount"] / df["ClaimNb"].sum()
)

vehicle_q4

,VehicleAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant,PolicyShare,ClaimShare
0,0-2,188140,79171.135348,5747,12299662.34,0.072590,2140.188331,Low Frequency,Low Severity,Low Frequency + Low Severity,0.277496,0.217327
1,3-5,132488,72038.123776,5344,10552899.23,0.074183,1974.719167,High Frequency,Low Severity,High Frequency + Low Severity,0.195413,0.202087
2,6-10,171587,99003.236361,8009,15805071.87,0.080896,1973.413893,High Frequency,Low Severity,High Frequency + Low Severity,0.253082,0.302866
3,11-15,134059,77987.995407,5680,17808346.08,0.072832,3135.272197,Low Frequency,High Severity,Low Frequency + High Severity,0.197730,0.214794
4,16-20,43396,25135.228607,1457,3010392.67,0.057966,2066.158318,Low Frequency,Low Severity,Low Frequency + Low Severity,0.064007,0.055098
5,21+,8321,5147.115965,207,432844.31,0.040217,2091.035314,Low Frequency,Low Severity,Low Frequency + Low Severity,0.012273,0.007828

In [173]:
df["VehPower"].describe()

count    677991.000000
mean          6.454649
std           2.050914
min           4.000000
25%           5.000000
50%           6.000000
75%           7.000000
max          15.000000
Name: VehPower, dtype: float64

In [174]:
df["VehPower"].value_counts().sort_index()

VehPower
4     115344
5     124815
6     148972
7     145398
8      46954
9      30084
10     31353
11     18352
12      8214
13      3229
14      2350
15      2926
Name: count, dtype: int64

In [175]:
df["VehiclePowerGroup"] = pd.cut(
    df["VehPower"],
    bins=[3, 5, 7, 10, 15],
    labels=[
        "4-5",
        "6-7",
        "8-10",
        "11-15"
    ],
    include_lowest=True
)

In [176]:
df["VehiclePowerGroup"].value_counts().sort_index()

VehiclePowerGroup
4-5      240159
6-7      294370
8-10     108391
11-15     35071
Name: count, dtype: int64

In [177]:
power_q4 = (
    df.groupby("VehiclePowerGroup", observed=True)
    .agg(
        PolicyCount=("IDpol", "count"),
        Exposure=("Exposure", "sum"),
        ClaimCount=("ClaimNb", "sum"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

power_q4["ClaimFrequency"] = (
    power_q4["ClaimCount"] / power_q4["Exposure"]
)

power_q4["AverageSeverity"] = np.where(
    power_q4["ClaimCount"] > 0,
    power_q4["TotalClaimCost"] / power_q4["ClaimCount"],
    0
)

In [178]:
power_q4["FrequencyLevel"] = np.where(
    power_q4["ClaimFrequency"] > portfolio_frequency,
    "High Frequency",
    "Low Frequency"
)

In [179]:
power_q4["SeverityLevel"] = np.where(
    power_q4["AverageSeverity"] > portfolio_severity,
    "High Severity",
    "Low Severity"
)

In [180]:
power_q4["RiskQuadrant"] = (
    power_q4["FrequencyLevel"]
    + " + "
    + power_q4["SeverityLevel"]
)

In [181]:
power_q4

,VehiclePowerGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant
0,4-5,240159,128238.526125,9118,18247830.57,0.071102,2001.297496,Low Frequency,Low Severity,Low Frequency + Low Severity
1,6-7,294370,160468.876873,11898,26812343.99,0.074145,2253.516893,High Frequency,Low Severity,High Frequency + Low Severity
2,8-10,108391,53405.480785,4082,12073030.49,0.076434,2957.626284,High Frequency,High Severity,High Frequency + High Severity
3,11-15,35071,16369.951681,1346,2776011.45,0.082224,2062.415639,High Frequency,Low Severity,High Frequency + Low Severity

In [182]:
high_risk_power = power_q4[
    power_q4["RiskQuadrant"] == "High Frequency + High Severity"
]

high_risk_power

,VehiclePowerGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant
2,8-10,108391,53405.480785,4082,12073030.49,0.076434,2957.626284,High Frequency,High Severity,High Frequency + High Severity

In [183]:
high_risk_power["PolicyShare"] = (
    high_risk_power["PolicyCount"] / df["IDpol"].nunique()
)

high_risk_power["ClaimShare"] = (
    high_risk_power["ClaimCount"] / df["ClaimNb"].sum()
)

high_risk_power

C:\Users\admin\AppData\Local\Temp\ipykernel_16020\2551632960.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  high_risk_power["PolicyShare"] = (
C:\Users\admin\AppData\Local\Temp\ipykernel_16020\2551632960.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  high_risk_power["ClaimShare"] = (

,VehiclePowerGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant,PolicyShare,ClaimShare
2,8-10,108391,53405.480785,4082,12073030.49,0.076434,2957.626284,High Frequency,High Severity,High Frequency + High Severity,0.159871,0.154364

In [184]:
high_risk_power["ClaimShare_to_PolicyShare"] = (
    high_risk_power["ClaimShare"] /
    high_risk_power["PolicyShare"]
)

high_risk_power

C:\Users\admin\AppData\Local\Temp\ipykernel_16020\3033092739.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  high_risk_power["ClaimShare_to_PolicyShare"] = (

,VehiclePowerGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant,PolicyShare,ClaimShare,ClaimShare_to_PolicyShare
2,8-10,108391,53405.480785,4082,12073030.49,0.076434,2957.626284,High Frequency,High Severity,High Frequency + High Severity,0.159871,0.154364,0.965554

In [185]:
high_risk_power = high_risk_power.copy()

In [186]:
high_risk_power["ClaimShare_to_PolicyShare"] = (
    high_risk_power["ClaimShare"] /
    high_risk_power["PolicyShare"]
)

high_risk_power

,VehiclePowerGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant,PolicyShare,ClaimShare,ClaimShare_to_PolicyShare
2,8-10,108391,53405.480785,4082,12073030.49,0.076434,2957.626284,High Frequency,High Severity,High Frequency + High Severity,0.159871,0.154364,0.965554

In [187]:
df["BonusMalusGroup"].value_counts().sort_index()

BonusMalusGroup
50         384142
51-60       94443
61-70       56928
71-80       61824
81-90       35724
91-100      37136
101-120      5554
121+         2240
Name: count, dtype: int64

In [188]:
bonus_q4 = (
    df.groupby("BonusMalusGroup", observed=True)
    .agg(
        PolicyCount=("IDpol", "count"),
        Exposure=("Exposure", "sum"),
        ClaimCount=("ClaimNb", "sum"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

bonus_q4["ClaimFrequency"] = (
    bonus_q4["ClaimCount"] / bonus_q4["Exposure"]
)

bonus_q4["AverageSeverity"] = np.where(
    bonus_q4["ClaimCount"] > 0,
    bonus_q4["TotalClaimCost"] / bonus_q4["ClaimCount"],
    0
)

In [189]:
bonus_q4["FrequencyLevel"] = np.where(
    bonus_q4["ClaimFrequency"] > portfolio_frequency,
    "High Frequency",
    "Low Frequency"
)

bonus_q4["SeverityLevel"] = np.where(
    bonus_q4["AverageSeverity"] > portfolio_severity,
    "High Severity",
    "Low Severity"
)

In [190]:
bonus_q4["RiskQuadrant"] = (
    bonus_q4["FrequencyLevel"]
    + " + "
    + bonus_q4["SeverityLevel"]
)

In [191]:
bonus_q4

,BonusMalusGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant
0,50,384142,225222.490903,11592,22282394.02,0.051469,1922.221706,Low Frequency,Low Severity,Low Frequency + Low Severity
1,51-60,94443,47983.227013,3576,7025420.41,0.074526,1964.603023,High Frequency,Low Severity,High Frequency + Low Severity
2,61-70,56928,26496.753500,3116,6091205.46,0.117599,1954.815616,High Frequency,Low Severity,High Frequency + Low Severity
3,71-80,61824,26566.663294,2798,6142659.22,0.105320,2195.374989,High Frequency,Low Severity,High Frequency + Low Severity
4,81-90,35724,15246.919478,1720,3657454.13,0.112810,2126.426820,High Frequency,Low Severity,High Frequency + Low Severity
5,91-100,37136,13395.462272,2386,12150153.70,0.178120,5092.268944,High Frequency,High Severity,High Frequency + High Severity
6,101-120,5554,2573.003003,800,1568366.06,0.310921,1960.457575,High Frequency,Low Severity,High Frequency + Low Severity
7,121+,2240,998.316000,456,991563.50,0.456769,2174.481360,High Frequency,Low Severity,High Frequency + Low Severity

In [192]:
high_risk_bonus = bonus_q4[
    bonus_q4["RiskQuadrant"] == "High Frequency + High Severity"
].copy()

In [193]:
high_risk_bonus["PolicyShare"] = (
    high_risk_bonus["PolicyCount"] / df["IDpol"].nunique()
)

high_risk_bonus["ClaimShare"] = (
    high_risk_bonus["ClaimCount"] / df["ClaimNb"].sum()
)

In [194]:
high_risk_bonus["ClaimShare_to_PolicyShare"] = (
    high_risk_bonus["ClaimShare"] /
    high_risk_bonus["PolicyShare"]
)

In [195]:
high_risk_bonus

,BonusMalusGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity,FrequencyLevel,SeverityLevel,RiskQuadrant,PolicyShare,ClaimShare,ClaimShare_to_PolicyShare
5,91-100,37136,13395.462272,2386,12150153.7,0.17812,5092.268944,High Frequency,High Severity,High Frequency + High Severity,0.054774,0.090228,1.647298

In [196]:
df["TotalClaimCost"].describe()

count    6.779910e+05
mean     8.836285e+01
std      5.822549e+03
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      4.075401e+06
Name: TotalClaimCost, dtype: float64

In [197]:
df["TotalClaimCost"].sort_values(ascending=False).head(10)

150015    4075400.56
54315     1404185.52
270605    1301172.60
416613     774411.50
203383     399213.66
368653     382955.14
147882     307096.42
75664      301635.49
396344     287423.00
431405     281897.49
Name: TotalClaimCost, dtype: float64

In [198]:
#Pareto Table
pareto = df[df["TotalClaimCost"] > 0][
    ["IDpol", "TotalClaimCost"]
].copy()

In [199]:
pareto = pareto.sort_values(
    "TotalClaimCost",
    ascending=False
).reset_index(drop=True)

In [200]:
pareto["CumulativeClaimCost"] = (
    pareto["TotalClaimCost"].cumsum()
)

In [201]:
total_claim_cost = pareto["TotalClaimCost"].sum()

pareto["CumulativeClaimCostShare"] = (
    pareto["CumulativeClaimCost"] / total_claim_cost
)

In [202]:
pareto["PolicyShare"] = (
    (pareto.index + 1) / len(pareto)
)

In [203]:
pareto.head(10)

,IDpol,TotalClaimCost,CumulativeClaimCost,CumulativeClaimCostShare,PolicyShare
0,1120377.0,4075400.56,4075400.56,0.068026,0.000040
1,110846.0,1404185.52,5479586.08,0.091465,0.000080
2,2141337.0,1301172.60,6780758.68,0.113184,0.000120
3,3122016.0,774411.50,7555170.18,0.126110,0.000160
4,2008127.0,399213.66,7954383.84,0.132774,0.000200
5,3025890.0,382955.14,8337338.98,0.139166,0.000241
6,1117644.0,307096.42,8644435.40,0.144292,0.000281
7,158309.0,301635.49,8946070.89,0.149327,0.000321
8,3075820.0,287423.00,9233493.89,0.154125,0.000361
9,3150210.0,281897.49,9515391.38,0.158830,0.000401

In [204]:
pareto_80 = pareto[
    pareto["CumulativeClaimCostShare"] >= 0.80
].iloc[0]

pareto_80

IDpol                       3.171467e+06
TotalClaimCost              1.204000e+03
CumulativeClaimCost         4.792770e+07
CumulativeClaimCostShare    8.000055e-01
PolicyShare                 3.939224e-01
Name: 9825, dtype: float64

In [205]:
n_80 = pareto[
    pareto["CumulativeClaimCostShare"] < 0.80
].shape[0] + 1

n_total = len(pareto)

share_80 = n_80 / n_total

n_80, n_total, share_80

(9826, 24944, 0.3939223861449647)

In [206]:
pareto.loc[
    pareto["CumulativeClaimCostShare"] >= 0.80,
    ["PolicyShare", "CumulativeClaimCostShare"]
].head(1)

      PolicyShare  CumulativeClaimCostShare
9825     0.393922                  0.800005

In [207]:
pareto_summary = pd.DataFrame({
    "Metric": [
        "Total Policies with Claims",
        "Policies Needed for 80% of Claim Cost",
        "Policy Share for 80% of Claim Cost"
    ],
    "Value": [
        len(pareto),
        n_80,
        share_80
    ]
})

pareto_summary

                                  Metric         Value
0             Total Policies with Claims  24944.000000
1  Policies Needed for 80% of Claim Cost   9826.000000
2     Policy Share for 80% of Claim Cost      0.393922

In [208]:
claim_amounts = df.loc[
    df["TotalClaimCost"] > 0,
    "TotalClaimCost"
]

claim_amounts.describe()

count    2.494400e+04
mean     2.401749e+03
std      3.026475e+04
min      1.000000e+00
25%      7.497875e+02
50%      1.172000e+03
75%      1.346400e+03
max      4.075401e+06
Name: TotalClaimCost, dtype: float64

In [209]:
Q1 = claim_amounts.quantile(0.25)
Q3 = claim_amounts.quantile(0.75)

IQR = Q3 - Q1

upper_bound = Q3 + 1.5 * IQR

Q1, Q3, IQR, upper_bound

(np.float64(749.7875),
 np.float64(1346.4),
 np.float64(596.6125000000001),
 np.float64(2241.3187500000004))

In [210]:
outlier_claims = df[
    df["TotalClaimCost"] > upper_bound
].copy()

In [211]:
len(outlier_claims)

3761

In [212]:
outlier_claim_share = (
    len(outlier_claims) / len(pareto)
)

outlier_claim_share

0.15077774214239897

In [213]:
outlier_claim_cost = outlier_claims["TotalClaimCost"].sum()

total_claim_cost = claim_amounts.sum()

outlier_cost_share = (
    outlier_claim_cost / total_claim_cost
)

outlier_claim_cost, outlier_cost_share

(np.float64(39289827.74), np.float64(0.6558227604261859))

In [214]:
outlier_by_age = (
    outlier_claims
    .groupby("DriverAgeGroup", observed=True)
    .agg(
        OutlierCount=("IDpol", "count"),
        OutlierClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

In [215]:
outlier_by_age

  DriverAgeGroup  OutlierCount  OutlierClaimCost
0          18-25           397       10527972.72
1          26-35           767        6735367.77
2          36-45           860        7152970.95
3          46-55           949        7186838.83
4          56-65           440        3596772.02
5            66+           348        4089905.45

In [216]:
age_outlier_analysis = (
    df.groupby("DriverAgeGroup", observed=True)
    .agg(
        TotalPolicies=("IDpol", "count"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

age_outlier_analysis = age_outlier_analysis.merge(
    outlier_by_age,
    on="DriverAgeGroup",
    how="left"
)

age_outlier_analysis["OutlierCount"] = (
    age_outlier_analysis["OutlierCount"].fillna(0)
)

age_outlier_analysis["OutlierClaimCost"] = (
    age_outlier_analysis["OutlierClaimCost"].fillna(0)
)

In [217]:
age_outlier_analysis["OutlierRate"] = (
    age_outlier_analysis["OutlierCount"] /
    age_outlier_analysis["TotalPolicies"]
)

age_outlier_analysis["OutlierCostShare"] = (
    age_outlier_analysis["OutlierClaimCost"] /
    age_outlier_analysis["TotalClaimCost"]
)

In [218]:
age_outlier_analysis

,DriverAgeGroup,TotalPolicies,TotalClaimCost,OutlierCount,OutlierClaimCost,OutlierRate,OutlierCostShare
0,18-25,38893,12307261.54,397,10527972.72,0.010207,0.855428
1,26-35,149180,10607248.80,767,6735367.77,0.005141,0.634978
2,36-45,170345,12119011.84,860,7152970.95,0.005049,0.590227
3,46-55,161895,12326494.29,949,7186838.83,0.005862,0.583040
4,56-65,90687,6267615.63,440,3596772.02,0.004852,0.573866
5,66+,66991,6281584.40,348,4089905.45,0.005195,0.651095

In [219]:
outlier_by_vehicle_age = (
    outlier_claims
    .groupby("VehicleAgeGroup", observed=True)
    .agg(
        OutlierCount=("IDpol", "count"),
        OutlierClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

outlier_by_vehicle_age

  VehicleAgeGroup  OutlierCount  OutlierClaimCost
0             0-2           877        7834854.60
1             3-5           830        6489860.17
2            6-10          1181        9610760.36
3           11-15           665       13288012.41
4           16-20           185        1805407.03
5             21+            23         260933.17

In [220]:
vehicle_age_outlier_analysis = (
    df.groupby("VehicleAgeGroup", observed=True)
    .agg(
        TotalPolicies=("IDpol", "count"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

vehicle_age_outlier_analysis = vehicle_age_outlier_analysis.merge(
    outlier_by_vehicle_age,
    on="VehicleAgeGroup",
    how="left"
)

vehicle_age_outlier_analysis["OutlierCount"] = (
    vehicle_age_outlier_analysis["OutlierCount"].fillna(0)
)

vehicle_age_outlier_analysis["OutlierClaimCost"] = (
    vehicle_age_outlier_analysis["OutlierClaimCost"].fillna(0)
)

In [221]:
vehicle_age_outlier_analysis["OutlierRate"] = (
    vehicle_age_outlier_analysis["OutlierCount"] /
    vehicle_age_outlier_analysis["TotalPolicies"]
)

vehicle_age_outlier_analysis["OutlierCostShare"] = (
    vehicle_age_outlier_analysis["OutlierClaimCost"] /
    vehicle_age_outlier_analysis["TotalClaimCost"]
)

In [222]:
vehicle_age_outlier_analysis

,VehicleAgeGroup,TotalPolicies,TotalClaimCost,OutlierCount,OutlierClaimCost,OutlierRate,OutlierCostShare
0,0-2,188140,12299662.34,877,7834854.60,0.004661,0.636998
1,3-5,132488,10552899.23,830,6489860.17,0.006265,0.614984
2,6-10,171587,15805071.87,1181,9610760.36,0.006883,0.608081
3,11-15,134059,17808346.08,665,13288012.41,0.004961,0.746168
4,16-20,43396,3010392.67,185,1805407.03,0.004263,0.599725
5,21+,8321,432844.31,23,260933.17,0.002764,0.602834

In [223]:
outlier_by_power = (
    outlier_claims
    .groupby("VehiclePowerGroup", observed=True)
    .agg(
        OutlierCount=("IDpol", "count"),
        OutlierClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

outlier_by_power

  VehiclePowerGroup  OutlierCount  OutlierClaimCost
0               4-5          1265       11157171.74
1               6-7          1676       17509307.72
2              8-10           600        8847685.41
3             11-15           220        1775662.87

In [224]:
power_outlier_analysis = (
    df.groupby("VehiclePowerGroup", observed=True)
    .agg(
        TotalPolicies=("IDpol", "count"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

power_outlier_analysis = power_outlier_analysis.merge(
    outlier_by_power,
    on="VehiclePowerGroup",
    how="left"
)

power_outlier_analysis["OutlierCount"] = (
    power_outlier_analysis["OutlierCount"].fillna(0)
)

power_outlier_analysis["OutlierClaimCost"] = (
    power_outlier_analysis["OutlierClaimCost"].fillna(0)
)

In [225]:
power_outlier_analysis["OutlierRate"] = (
    power_outlier_analysis["OutlierCount"] /
    power_outlier_analysis["TotalPolicies"]
)

power_outlier_analysis["OutlierCostShare"] = (
    power_outlier_analysis["OutlierClaimCost"] /
    power_outlier_analysis["TotalClaimCost"]
)

In [226]:
power_outlier_analysis

,VehiclePowerGroup,TotalPolicies,TotalClaimCost,OutlierCount,OutlierClaimCost,OutlierRate,OutlierCostShare
0,4-5,240159,18247830.57,1265,11157171.74,0.005267,0.611425
1,6-7,294370,26812343.99,1676,17509307.72,0.005694,0.653032
2,8-10,108391,12073030.49,600,8847685.41,0.005536,0.732847
3,11-15,35071,2776011.45,220,1775662.87,0.006273,0.639645

In [227]:
outlier_by_bonus = (
    outlier_claims
    .groupby("BonusMalusGroup", observed=True)
    .agg(
        OutlierCount=("IDpol", "count"),
        OutlierClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

outlier_by_bonus

  BonusMalusGroup  OutlierCount  OutlierClaimCost
0              50          1526       13271252.86
1           51-60           507        4350203.78
2           61-70           431        3540100.99
3           71-80           430        3965221.78
4           81-90           259        2318203.82
5          91-100           424       10337283.90
6         101-120           118         897304.60
7            121+            66         610256.01

In [228]:
bonus_outlier_analysis = (
    df.groupby("BonusMalusGroup", observed=True)
    .agg(
        TotalPolicies=("IDpol", "count"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

bonus_outlier_analysis = bonus_outlier_analysis.merge(
    outlier_by_bonus,
    on="BonusMalusGroup",
    how="left"
)

bonus_outlier_analysis["OutlierCount"] = (
    bonus_outlier_analysis["OutlierCount"].fillna(0)
)

bonus_outlier_analysis["OutlierClaimCost"] = (
    bonus_outlier_analysis["OutlierClaimCost"].fillna(0)
)

In [229]:
bonus_outlier_analysis["OutlierRate"] = (
    bonus_outlier_analysis["OutlierCount"] /
    bonus_outlier_analysis["TotalPolicies"]
)

bonus_outlier_analysis["OutlierCostShare"] = (
    bonus_outlier_analysis["OutlierClaimCost"] /
    bonus_outlier_analysis["TotalClaimCost"]
)

In [230]:
bonus_outlier_analysis

,BonusMalusGroup,TotalPolicies,TotalClaimCost,OutlierCount,OutlierClaimCost,OutlierRate,OutlierCostShare
0,50,384142,22282394.02,1526,13271252.86,0.003972,0.595594
1,51-60,94443,7025420.41,507,4350203.78,0.005368,0.619209
2,61-70,56928,6091205.46,431,3540100.99,0.007571,0.581182
3,71-80,61824,6142659.22,430,3965221.78,0.006955,0.645522
4,81-90,35724,3657454.13,259,2318203.82,0.007250,0.633830
5,91-100,37136,12150153.70,424,10337283.90,0.011417,0.850794
6,101-120,5554,1568366.06,118,897304.60,0.021246,0.572127
7,121+,2240,991563.50,66,610256.01,0.029464,0.615448

In [231]:
df.columns.tolist()

['IDpol',
 'ClaimNb',
 'Exposure',
 'VehPower',
 'VehAge',
 'DrivAge',
 'BonusMalus',
 'VehBrand',
 'VehGas',
 'Area',
 'Density',
 'Region',
 'ClaimCount_Severity',
 'TotalClaimCost',
 'AverageClaimSeverity',
 'MaxClaimAmount',
 'DriverAgeGroup',
 'VehicleAgeGroup',
 'BonusMalusGroup',
 'VehiclePowerGroup']

In [232]:
overview_table = pd.DataFrame({
    "PolicyCount": [df["IDpol"].nunique()],
    "TotalExposure": [df["Exposure"].sum()],
    "TotalClaimCount": [df["ClaimNb"].sum()],
    "TotalClaimCost": [df["TotalClaimCost"].sum()],
    "ClaimFrequency": [df["ClaimNb"].sum() / df["Exposure"].sum()],
    "AverageClaimSeverity": [
        df["TotalClaimCost"].sum() / df["ClaimNb"].sum()
    ]
})

overview_table

,PolicyCount,TotalExposure,TotalClaimCount,TotalClaimCost,ClaimFrequency,AverageClaimSeverity
0,677991,358482.835463,26444,59909216.5,0.073766,2265.512649

In [233]:
risk_driver_age = (
    df.groupby("DriverAgeGroup", observed=True)
    .agg(
        PolicyCount=("IDpol", "count"),
        Exposure=("Exposure", "sum"),
        ClaimCount=("ClaimNb", "sum"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

risk_driver_age["ClaimFrequency"] = (
    risk_driver_age["ClaimCount"] /
    risk_driver_age["Exposure"]
)

risk_driver_age["AverageSeverity"] = np.where(
    risk_driver_age["ClaimCount"] > 0,
    risk_driver_age["TotalClaimCost"] /
    risk_driver_age["ClaimCount"],
    0
)

risk_driver_age

,DriverAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,18-25,38893,16226.113263,2403,12307261.54,0.148095,5121.623612
1,26-35,149180,69265.528075,5167,10607248.80,0.074597,2052.883453
2,36-45,170345,87695.996287,6315,12119011.84,0.072010,1919.083427
3,46-55,161895,89265.746408,6622,12326494.29,0.074183,1861.445831
4,56-65,90687,51772.833261,3316,6267615.63,0.064049,1890.113278
5,66+,66991,44256.618168,2621,6281584.40,0.059223,2396.636551

In [234]:
risk_vehicle_age = (
    df.groupby("VehicleAgeGroup", observed=True)
    .agg(
        PolicyCount=("IDpol", "count"),
        Exposure=("Exposure", "sum"),
        ClaimCount=("ClaimNb", "sum"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

risk_vehicle_age["ClaimFrequency"] = (
    risk_vehicle_age["ClaimCount"] /
    risk_vehicle_age["Exposure"]
)

risk_vehicle_age["AverageSeverity"] = np.where(
    risk_vehicle_age["ClaimCount"] > 0,
    risk_vehicle_age["TotalClaimCost"] /
    risk_vehicle_age["ClaimCount"],
    0
)

risk_vehicle_age

,VehicleAgeGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,0-2,188140,79171.135348,5747,12299662.34,0.072590,2140.188331
1,3-5,132488,72038.123776,5344,10552899.23,0.074183,1974.719167
2,6-10,171587,99003.236361,8009,15805071.87,0.080896,1973.413893
3,11-15,134059,77987.995407,5680,17808346.08,0.072832,3135.272197
4,16-20,43396,25135.228607,1457,3010392.67,0.057966,2066.158318
5,21+,8321,5147.115965,207,432844.31,0.040217,2091.035314

In [235]:
risk_vehicle_power = (
    df.groupby("VehiclePowerGroup", observed=True)
    .agg(
        PolicyCount=("IDpol", "count"),
        Exposure=("Exposure", "sum"),
        ClaimCount=("ClaimNb", "sum"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

risk_vehicle_power["ClaimFrequency"] = (
    risk_vehicle_power["ClaimCount"] /
    risk_vehicle_power["Exposure"]
)

risk_vehicle_power["AverageSeverity"] = np.where(
    risk_vehicle_power["ClaimCount"] > 0,
    risk_vehicle_power["TotalClaimCost"] /
    risk_vehicle_power["ClaimCount"],
    0
)

risk_vehicle_power

,VehiclePowerGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,4-5,240159,128238.526125,9118,18247830.57,0.071102,2001.297496
1,6-7,294370,160468.876873,11898,26812343.99,0.074145,2253.516893
2,8-10,108391,53405.480785,4082,12073030.49,0.076434,2957.626284
3,11-15,35071,16369.951681,1346,2776011.45,0.082224,2062.415639

In [236]:
risk_bonus_malus = (
    df.groupby("BonusMalusGroup", observed=True)
    .agg(
        PolicyCount=("IDpol", "count"),
        Exposure=("Exposure", "sum"),
        ClaimCount=("ClaimNb", "sum"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

risk_bonus_malus["ClaimFrequency"] = (
    risk_bonus_malus["ClaimCount"] /
    risk_bonus_malus["Exposure"]
)

risk_bonus_malus["AverageSeverity"] = np.where(
    risk_bonus_malus["ClaimCount"] > 0,
    risk_bonus_malus["TotalClaimCost"] /
    risk_bonus_malus["ClaimCount"],
    0
)

risk_bonus_malus

,BonusMalusGroup,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,50,384142,225222.490903,11592,22282394.02,0.051469,1922.221706
1,51-60,94443,47983.227013,3576,7025420.41,0.074526,1964.603023
2,61-70,56928,26496.753500,3116,6091205.46,0.117599,1954.815616
3,71-80,61824,26566.663294,2798,6142659.22,0.105320,2195.374989
4,81-90,35724,15246.919478,1720,3657454.13,0.112810,2126.426820
5,91-100,37136,13395.462272,2386,12150153.70,0.178120,5092.268944
6,101-120,5554,2573.003003,800,1568366.06,0.310921,1960.457575
7,121+,2240,998.316000,456,991563.50,0.456769,2174.481360

In [237]:
risk_region = (
    df.groupby("Region", observed=True)
    .agg(
        PolicyCount=("IDpol", "count"),
        Exposure=("Exposure", "sum"),
        ClaimCount=("ClaimNb", "sum"),
        TotalClaimCost=("TotalClaimCost", "sum")
    )
    .reset_index()
)

risk_region["ClaimFrequency"] = (
    risk_region["ClaimCount"] /
    risk_region["Exposure"]
)

risk_region["AverageSeverity"] = np.where(
    risk_region["ClaimCount"] > 0,
    risk_region["TotalClaimCost"] /
    risk_region["ClaimCount"],
    0
)

risk_region

,Region,PolicyCount,Exposure,ClaimCount,TotalClaimCost,ClaimFrequency,AverageSeverity
0,Alsace,2200,1209.115823,92,121424.99,0.076089,1319.836848
1,Aquitaine,31329,14322.166692,1055,1916138.54,0.073662,1816.245062
2,Auvergne,5287,2322.884229,141,183974.83,0.060700,1304.786028
3,Basse-Normandie,10892,6657.801142,452,929847.31,0.067890,2057.184314
4,Bourgogne,10491,5025.098609,345,636298.04,0.068655,1844.342145
5,Bretagne,42120,27752.443675,1871,3901051.25,0.067417,2085.008685
6,Centre,160595,102707.853386,6475,19074802.36,0.063043,2945.915422
7,Champagne-Ardenne,3025,1204.881509,77,481248.34,0.063907,6249.978442
8,Corse,4516,1765.935399,132,464582.55,0.074748,3519.564773
9,Franche-Comte,1326,564.012946,38,76534.11,0.067374,2014.055526
10,Haute-Normandie,8784,3177.682181,220,327493.58,0.069233,1488.607182
11,Ile-de-France,69789,30207.161954,2591,4563221.86,0.085774,1761.181729
12,Languedoc-Roussillon,35805,14736.104177,1068,2030911.08,0.072475,1901.602135
13,Limousin,4567,2395.994542,197,280285.14,0.082221,1422.767208
14,Lorraine,12990,8113.777972,468,1034301.30,0.057680,2210.045513
15,Midi-Pyrenees,17141,7020.108555,369,539385.27,0.052563,1461.748699
16,Nord-Pas-de-Calais,27284,11496.974269,944,1634689.72,0.082109,1731.662839
17,Pays-de-la-Loire,38747,21931.151165,1576,2570964.93,0.071861,1631.322925
18,Picardie,7994,3574.410221,314,687624.87,0.087847,2189.888121
19,Poitou-Charentes,19046,11163.408715,800,1305107.78,0.071663,1631.384725
20,Provence-Alpes-Cotes-D'Azur,79315,35790.321015,2986,6871024.80,0.083430,2301.079973
21,Rhone-Alpes,84748,45343.547286,4233,10278303.85,0.093354,2428.136983

In [238]:
print([
    name for name in globals()
    if isinstance(globals()[name], pd.DataFrame)
])

['_', '__', '___', 'freq', 'sev', '_3', '_4', '_5', '_6', '_13', '_14', '_21', '_22', '_28', '_29', '_31', '_32', 'duplicate_groups', '_33', '_34', '_35', '_36', 'severity_counts', 'check', '_57', '_59', 'severity_count', 'freq_check', 'claim_summary', '_62', 'df', 'kpi', '_75', 'region_analysis', '_79', '_80', '_81', '_82', 'age_analysis', '_85', 'vehicle_age_analysis', '_87', 'fuel_analysis', '_88', 'pareto', 'outliers', '_94', 'zero_exposure', '_107', '_108', '_109', '_110', '_111', '_112', 'region_rank', '_113', '_114', 'vehage_100', '_126', '_127', '_128', '_130', '_131', '_132', 'power_analysis', '_133', '_134', '_135', '_137', '_138', '_139', '_141', '_142', '_143', '_144', '_145', 'bonus_analysis', '_149', '_150', '_151', 'bonus_q4', '_153', 'high_risk_bonus', '_154', 'driver_q4', '_155', 'high_risk_driver', '_156', 'risk_summary', '_158', '_159', '_160', '_161', 'vehicle_q4', '_167', 'high_risk_vehicle', '_168', '_170', '_172', 'power_q4', '_181', 'high_risk_power', '_182', '_183', '_184', '_186', '_191', '_195', '_203', '_206', 'pareto_summary', '_207', 'outlier_claims', 'outlier_by_age', '_215', 'age_outlier_analysis', '_218', 'outlier_by_vehicle_age', '_219', 'vehicle_age_outlier_analysis', '_222', 'outlier_by_power', '_223', 'power_outlier_analysis', '_226', 'outlier_by_bonus', '_227', 'bonus_outlier_analysis', '_230', 'overview_table', '_232', 'risk_driver_age', '_233', 'risk_vehicle_age', '_234', 'risk_vehicle_power', '_235', 'risk_bonus_malus', '_236', 'risk_region', '_237']

In [239]:
import pandas as pd

output_file = "Insurance_Tableau_Data.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

    # 1. Final dataset
    df.to_excel(
        writer,
        sheet_name="Final_Data",
        index=False
    )

    # 2. Portfolio Overview
    overview_table.to_excel(
        writer,
        sheet_name="Overview",
        index=False
    )

    # 3. Risk by Driver Age
    risk_driver_age.to_excel(
        writer,
        sheet_name="Driver_Age",
        index=False
    )

    # 4. Risk by Vehicle Age
    risk_vehicle_age.to_excel(
        writer,
        sheet_name="Vehicle_Age",
        index=False
    )

    # 5. Risk by Vehicle Power
    risk_vehicle_power.to_excel(
        writer,
        sheet_name="Vehicle_Power",
        index=False
    )

    # 6. Risk by Bonus-Malus
    risk_bonus_malus.to_excel(
        writer,
        sheet_name="Bonus_Malus",
        index=False
    )

    # 7. Risk by Region
    risk_region.to_excel(
        writer,
        sheet_name="Region",
        index=False
    )

    # 8. Pareto / Claim Cost Concentration
    pareto_summary.to_excel(
        writer,
        sheet_name="Pareto",
        index=False
    )

    # 9. Outliers by Driver Age
    age_outlier_analysis.to_excel(
        writer,
        sheet_name="Outlier_Driver_Age",
        index=False
    )

    # 10. Outliers by Vehicle Age
    vehicle_age_outlier_analysis.to_excel(
        writer,
        sheet_name="Outlier_Vehicle_Age",
        index=False
    )

    # 11. Outliers by Vehicle Power
    power_outlier_analysis.to_excel(
        writer,
        sheet_name="Outlier_Vehicle_Power",
        index=False
    )

    # 12. Outliers by Bonus-Malus
    bonus_outlier_analysis.to_excel(
        writer,
        sheet_name="Outlier_Bonus_Malus",
        index=False
    )

print("Excel file created successfully:")
print(output_file)

Excel file created successfully:
Insurance_Tableau_Data.xlsx

In [240]:
print("TotalClaimCost zero:", (df["TotalClaimCost"] == 0).sum())
print("TotalClaimCost non-zero:", (df["TotalClaimCost"] > 0).sum())

print("AverageClaimSeverity zero:", (df["AverageClaimSeverity"] == 0).sum())
print("AverageClaimSeverity non-zero:", (df["AverageClaimSeverity"] > 0).sum())

print("ClaimCount_Severity zero:", (df["ClaimCount_Severity"] == 0).sum())
print("ClaimCount_Severity non-zero:", (df["ClaimCount_Severity"] > 0).sum())

TotalClaimCost zero: 653047
TotalClaimCost non-zero: 24944
AverageClaimSeverity zero: 653047
AverageClaimSeverity non-zero: 24944
ClaimCount_Severity zero: 653047
ClaimCount_Severity non-zero: 24944